### ISSUE TITLE
ChaCha20 database encryption support

### ISSUE THREAD

**Issue by hungover** [subdavis/Tusk#103]
## This issue is a 

- [x] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Tusk does not support the ChaCha20 database encryption algorithm. I had selected ChaCha20 during my database setup but Tusk could not access it, only giving me an invalid key error. I had to toggle database encryption to AES/Rijndael to get it to work.

### Please describe how you think it should change.

Please consider adding ChaCha20 encryption support, or a warning message that it is not supported.

**Comment by subdavis** [comment]
@hungover Please see #101 

This issue has been solved in #102 

The fix will be pushed to the google chrome and firefox stores sometime this weekend.  Thanks.

**Comment by hungover** [comment]
Sorry, I missed the closed issues. Thanks!
