### ISSUE TITLE
Add support for opening URL from keepass file

### ISSUE THREAD

**Issue by marsanyi** [subdavis/Tusk#104]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

One of the use cases I have for KeePass is to store a site's URL (usually the auth page) in the entry, then open the page directly from KeePass.  My memory is getting worse, so it's nice to be able not to have to remember URLs.

### Please describe how you think it should change.

Add another button to the retrieved entries that, when clicked, navigates to the entry's stored URL.  This would be used with the "find" function to find a specific entry.

**Comment by subdavis** [comment]
Great suggestion!  Will look into it :)

**Comment by subdavis** [comment]
Hey there, @marsanyi 

Please check out #105 and see if that will work for you.  I didn't think it was appropriate to add another large button to the list view, so you can click on an entry in search and get to the link from there.
