### ISSUE TITLE
Support for custom file's extensions

### ISSUE THREAD

**Issue by japko** [subdavis/Tusk#108]
## Feature request

 [ ] bug
 [ x] feature
 [ ] question

### Please describe the current behavior, and explain why it's bad.

I cannot use files with custom extensions. 
Keeping KeePass DB named with one of two extensions (kdb, kdbx) makes it easy to search for and it's pretty obvious whats inside when you list files and see .kdbx file. 

KeePass Windows (https://keepass.info) lets you use basically any file. Your DB can be named "beautiful_landscape.jpg" and program doesn't have a problem with opening that file.

### Please describe how you think it should change.

If it's possible please omit checking file's extension and just load file as KeePass DB.

**Comment by subdavis** [comment]
There is no way to search a cloud provider for a KeePass file if it doesn't have the proper extension.

So if you have that JPG in Google drive, Tusk will never find it.

I don't see a single reason for putting the wrong extension on your KeePass database anyway, unless you're a fan of "security by obscurity" (which I am absolutely not)

Thanks for your interest in tusk, but this just isn't practical.
