### ISSUE TITLE
Support multiple URLS

### ISSUE THREAD

**Issue by lsouchet** [subdavis/Tusk#109]
## This issue is a 

- [ ] bug
- [X] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
I use a keeweb to manage my keepass db.
For services using SSO (Single Sign On), there are several urls that should correspond to the same entry (user, password).
On keeweb, such entries are filled with all the urls in additional fields.
On Tusk (and in CKP), when trying to log on one of those sites, the automatic search for entries does not find any close match. However when entering the website url in the "search entire database" I can find the desired entry.
So it appears that Tusk manages to find the custom field when using the "search entire database" feature, but cannot find it by itself.

### Please describe how you think it should change.
In ideal use case, Tusk should propose the sso entry when logging to any website whose URL is referred to in a custom field.

**Comment by subdavis** [comment]
Solved in #85

Please see the readme: you want the `TUSK_URLS` custom field.

Please let me know if this solves your issue

**Comment by subdavis** [comment]
Closing due to no response.

**Comment by lsouchet** [comment]
Thanks, I got it working!
