### ISSUE TITLE
Hotkey to open Tusk

### ISSUE THREAD

**Issue by skylineKid712** [subdavis/Tusk#110]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
Currently you have to click the extension button near the address bar to open Tusk

### Please describe how you think it should change.
It would be nice to have a hotkey like CTRL + SHIFT + SPACE to open Tusk, similar to how CKP works

**Comment by subdavis** [comment]
There is one, same as CKP.

It doesn't work on chrome for Linux because of a bug in chrome for Linux.  

What browser are you using and what OS?

**Comment by skylineKid712** [comment]
Ok I tried it on Firefox and it works. I had been trying it on Chrome and Opera (Opera can run Chrome extensions in case you didn't know) and it's not working for me. I'm on Windows 10.

**Comment by subdavis** [comment]
Can you see that hotkeys are working for other chrome extensions? I installed CKP on chrome and it doesn't work either, which leads me to believe that this may be a chrome regression bug?

Firefox works fine, but no hotkeys are working on any extensions for me.

**Comment by skylineKid712** [comment]
CKP hotkey works fine for me on Chrome v64.0.3282.186 and Opera v51.0.2830.40. What extensions with hotkeys are you using that I could test out?

**Comment by agilgur5** [comment]
Similarly is not working for me on Chrome v64.0.3282.140 on Mac.

Also as far as I could tell, it didn't seem like this hotkey was documented anywhere (besides being listed in the manifests). I think it would be good to list it in one of the UIs, docs, etc.

**Comment by ahsquared** [comment]
Just wanted to add that the hotkey works in CKP. I just switched away from CKP to try Tusk, which I really like by the way, but the hotkey to open it doesn't work. Maybe looking back at how CKP does it (if different) could help? I'm on Chrome Version 66.0.3359.181 on OSX 10.13.4

**Comment by subdavis** [comment]
Good find, ahsquared!  This will definitely help me solve it :)
