### ISSUE TITLE
Hard-coded references to Chrome in UI

### ISSUE THREAD

**Issue by vjon** [subdavis/Tusk#112]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Currently, the UI is hard-coded to refer to the browser as "Chrome" in a number of places, which causes an inconsistent user experience for Firefox users (or other users if Tusk is ported further in the future).

### Please describe how you think it should change.

One of two possible approaches:
- Quick fix: Make references generic ("Until the browser exits")
- Full fix: Parameterize references and alter at packaging time

### Anything else?

If desired, I can work on this after an approach is decided upon.

**Comment by subdavis** [comment]
Could you explain what user experiences are "inconsistent"?

Chrome is a direct alias of "browser" in Firefox and exposes all of the same APIs.  So everywhere you see chrome, Firefox interprets this as 'browser'

**Comment by vjon** [comment]
Here, I'm not referring to APIs, but to the actual text presented to the user. For example, the Manage Keyfiles settings page has text like "Tusk can store your key files locally in Chrome storage...", and I'm proposing that it should read like "Tusk can store your key files locally in your browser's storage..." or similar.

**Comment by subdavis** [comment]
Oh sure, I can go through the source and scrub references to Chrome.  Thanks for opening this issue

**Comment by vjon** [comment]
If you like, I can knock this one out pretty quickly, just replacing the text with "your browser" or similar.

**Comment by subdavis** [comment]
You're more than welcome to tackle any issue in the tracker :)

I should start assigning ones I'm working on to moi so as not to confuse would-be contributors.
