### ISSUE TITLE
Add setting to disable notifications

### ISSUE THREAD

**Issue by agilgur5** [subdavis/Tusk#116]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Currently it requires notifications permissions and always sends desktop notifications. Desktop notifications are distracting and I typically only have them enabled for important/immediate things like email, Slack, calls. If my password manager has cleared the clipboard entry of my password, I don't particularly care to be notified of that.

### Please describe how you think it should change.

Add a setting to turn off the notifications. Consider making it opt-in instead of opt-out (would be a breaking change, but would also require less permissions)

### Anything else?

Thanks for making this, got referred to here since CKP is no longer maintained. Might be willing to implement this feature myself when I get some time since it seems simple.

**Comment by subdavis** [comment]
I think that's a great suggestion!
