### ISSUE TITLE
Synology webdav server error

### ISSUE THREAD

**Issue by Matt-Gyver** [subdavis/Tusk#117]
## This issue is a 

- [X] bug
- [ ] feature
- [ ] question
- [x] misunderstanding

### Please describe the current behavior, and explain why it's bad.
- I download and install Tusk addon on mozilla firefox 58.0.2 (archlinux)
- I configure a webdav server on synology 214+ (DSM 6.1-15047 Update 2 - webdav server 2.3.3-0024 (http and https)
- I create a user and give permission to access the webdav server
- I test with Dolphin on Archlinux and It works 
- I configure Tusk to use webdav (beta) with an internal link like webdav://10.10.10.10:5005/folder/to/db.kdbx
- I have this message :
Error: Type error for parameter permissions (Error processing origins.0: Value "webdav://10.10.10.10:5005/folder/to/db.kdbx" must either: be one of ["<all_urls>"], match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/) for permissions.request.
and the same error with https :
webdavs://10.10.10.10:5006/folder/to/db.kdbx

and this error when I use :
http://10.10.10.10:5005/folder/to/db.kdbx
https://10.10.10.10:5006/folder/to/db.kdbx
Error: Invalid response: 400 Bad Request

Did I do something wrong ?

Thank you for you work !

Regards,

Matt

**Comment by subdavis** [comment]
Yes, you should not use the full path to the file.  You should use the base url of the server in the URL field with http or https.

I've not tested Synology, but I would recommend you try:

Url: http://10.10.10.10:5005
User: user
Pass: pass

And allow tusk to scan your directory contents.  This is also poor documentation on my part, so I'll work on making this more clear in the official release of webDAV.  It would probably also be clever to parse the URL for these sorts of errors.

**Comment by Matt-Gyver** [comment]
hello,

Thank you ! It works :)

Solution :
Url: http://10.10.10.10:5005
or
Url: https://10.10.10.10:5005
User: user
Pass: pass

doesn't work with webdav:// or webdavs://

Regards

Matt
