### ISSUE TITLE
Add a hotkey to automatically fill login and password

### ISSUE THREAD

**Issue by Lawton-C** [subdavis/Tusk#119]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
The hotkey feature (Command + Shift + Space on a Mac) to open the Tusk is helpful. However I think the hotkey feature could go a step further.

### Please describe how you think it should change.
It would be great if there was a way to automatically fill in the login and password with a single keystroke

### Anything else?
That's it! Thanks for the nifty program!

**Comment by subdavis** [comment]
Back before the Tusk rewrite, you could tap the enter key to autofill the first suggestion.

I need to add that feature back in...

Thanks!

**Comment by kikers25** [comment]
That would be very nice :)

**Comment by barajus** [comment]
That would be amazing !
Keep up the good work 👍

**Comment by subdavis** [comment]
this has been released to google webstore and firefox addon store.  Documentation to enable this optional feature: https://github.com/subdavis/Tusk/wiki/User-Interaction

**Comment by kikers25** [comment]
It works like a charm. Thank you. You are awesome!
