### ISSUE TITLE
Fields Correctly Updated but not accepted by Sites which require Keyboard Activity

### ISSUE THREAD

**Issue by dbareis** [subdavis/Tusk#121]
As an example have a look at this website (the one the attached picture was taken of, actually I can't work out how to attach it...): "### https://secure.agl.com.au/login?client=8NReZXmds46C4pCMhOCN8mbHjQ60F9zh&protocol=oauth2&redirect_uri=https%3A%2F%2Fwww.agl.com.au%2Fsts%2Faccount%2Flogincallback&response_type=code&scope=openid&nonce=63966f346b61874cd92fa0d87169073b0d42ee1e8240e86655edcb8cfb0777b6&register=false&state=pS4xqlLuCX6Rjk_X9g-r2IH_nFHyFiDI#/login/identifier"

If case that doesn't work its the "residential" customer logon (**not their main one**), the field in the picture starts with the text "Password" and as soon as you start typing that disappears and things work.  When filled in with the magic wand, you can see that both items display at the same time and it won't accept the values.

As a workaround you can type a character and backspace to remove it.

**Comment by subdavis** [comment]
as I don't have a valid account with this application, I have no way of reaching the password prompt.

**Comment by subdavis** [comment]
Closed due to inactivity and no steps to reproduce.
