### ISSUE TITLE
digest authentication for WebDAV

### ISSUE THREAD

**Issue by kleinfelter** [subdavis/Tusk#124]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

It looks like Tusk uses only basic auth for WebDAV.  I set up a WebDAV share, I validated that it worked with my Tusk user ID/pass using another WebDAV client.  When I use the same URL, ID, and password with Tusk, my Apache error log says "client used wrong authentication scheme `Basic': /tusk/"

### Please describe how you think it should change.

I really don't want to be sending my WebDAV credentials in basic auth on http (and yes, it would only be my tusk WebDAV, but security is a multi-layered thing).

**Comment by subdavis** [comment]
This is a great suggestion, but not a feature I'm likely to get around to implementing in the near future. 

In the meantime, consider implementing SSL on your webdav share.

Thanks!
