### ISSUE TITLE
Let Tusk "click" on the login button

### ISSUE THREAD

**Issue by Flore-mozfr** [subdavis/Tusk#127]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

Hello !
I would like Tusk to be able to "click" on the login button as soon as login and password are completed. The previous extension I used with keepass did that and it is the only feature I miss on Tusk.
The click on the magic wand would be fill and submit login form.

Thanks for the work already done :+1:

**Comment by subdavis** [comment]
Thanks for the suggestion, and for being a user :)

I don't often give feature requests a hard "no" but I think this feature has potentially dangerous consequences.

Tusk is good, but in the event that it accidentally fills your password into the wrong place and presses the wrong button, you could end up with your login credentials on a forum post or social media or some other weird place where you can't remove them.

I very much like the momentary human intervention required to click "login" - sort of a checks and balances system where Tusk does 90% of the work but still needs your final input.

I hope this isn't a make-or-break feature for you!

**Comment by Flore-mozfr** [comment]
I never thought of that, I totally understand the reason behind your hard "no". I am usually careful when logging somewhere, but "usually" is not enough. And not enough for potentially putting my credentials at risk.
Thanks for your answer and don't worry, I will stay a user of tusk, just going to click on login / submit whatever. Anyway I still have to enter the 2FA after (whenever available)...
