### ISSUE TITLE
Open not only .kdbx files

### ISSUE THREAD

**Issue by viper-666** [subdavis/Tusk#129]
## This issue is a 

- [ ] bug
- [ x] feature
- [ ] question

Hello,
I named my keepass file xxx.jpg so you don't immediately see that this is a password file.
With Trusk I can't use this file because it returns the error message "this is not a keepass 4x file".
But this is not true, if I rename the file to xxx.kdbx the file can be opened.
Can you modify Trusk so that you can open all files?

**Comment by subdavis** [comment]
It makes no sense to name your keepass file `xxx.jpg`.  There is absolutely no security benefit from doing this. 

If you don't understand why, read https://en.wikipedia.org/wiki/List_of_file_signatures

File extensions are for users and programs to conveniently identify files.  However, bits of data called magic numbers will immediately give your `jpg` file away as not being a real image.

Finally, this has been requested before in #108 and I provide further explanation there.

You should just name your keepass database `*.kdbx`.  I won't be implementing this.
