### ISSUE TITLE
Feature Request: Allow multiple database files to be unlocked/searched simultaneously

### ISSUE THREAD

**Issue by tbradsha** [subdavis/Tusk#137]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

One must lock a database to switch to a different one.

### Please describe how you think it should change.

It'd be nice to search multiple databases simultaneously (e.g. work and home).

### Anything else?

As a sidenote, perhaps in the settings it'd be nice to select which ones are available to switch between/unlock. For example, currently if there are several database files in a WebDAV folder, they all show as options to switch to, even if I only want to see one or two of them on this computer.

**Comment by subdavis** [comment]
This would require major changes to almost every element of the UI.  Based on my time and interests, and the number of people that care about this feature, I can pretty safely say this feature, while a nice idea, will not be implemented.

Tusk is not intended as a full replacement for KeeWeb or KeePassXC.
