### ISSUE TITLE
Feature request: Support autotype

### ISSUE THREAD

**Issue by tbradsha** [subdavis/Tusk#138]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

There is not currently any auto-type behaviour.

### Please describe how you think it should change.

This would allow for better autofilling (e.g. multi-page logins). See for example these options:
https://github.com/keeweb/keeweb/wiki/Auto-Type

**Comment by subdavis** [comment]
This is impossible for a web extension.  There is no programmatic exposure to the OS to send keystrokes.

It only works on the desktop version of KeeWeb.
