### ISSUE TITLE
charginx kdbx through url

### ISSUE THREAD

**Issue by xenofree** [subdavis/Tusk#143]
Hi,

- [x] bug
- [ ] feature
- [ ] question

I try to acces to my .kdbx through nginx. Everything seems to work well. I can GET the file and i can PUT new file on my server.
But i can't access to it through Tusk.

I successfully entered my url and user/password on Tusk parameters (https://mydomain.com/database.kdbx), but the scan button don't seems to do anything for me. 

I have this log on my nginx.

 "PROPFIND /xxxx.kdbx HTTP/1.1" 207 589 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

And that's all. Tusk doesn't import my database.

**Comment by subdavis** [comment]
I assume you're using webDAV?

Please read https://github.com/subdavis/Tusk/wiki/WebDAV Support

Specifically, you don't put the URL of your KeePass db, just the base url of the server.

You could also use a shared url with http authentication.  Http://user:pass@server.com/path/to/file.kdbx

I recommend using webDAV though.
