### ISSUE TITLE
My databases fall behind when I cannot find out the exact storage address of the database being used

### ISSUE THREAD

**Issue by kewlguy2** [subdavis/Tusk#144]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
I have 5 Google GSuite accounts plus my personal account. Keeping track of the location of my database is a REAL pain when I look at the settings for Tusk it shows me the name of the database in use though does not give me any idea of what account or the actual address of the database. 

Lately google has taken to kicking my Tusk out of the one drive I use to store the database, when I am using a different account with Google, so, now I am ending up with copies I would like to eliminate though cannot because I am unsure which storage location is currently in use.
![selection_981-thumb](https://user-images.githubusercontent.com/2295825/39386157-77f361e2-4a30-11e8-9121-9614ead0043f.png)

I am up for any solution that makes this easier after copies have been created for any expedient reason that is now causing a new issue.

Thanks for listening.

**Comment by subdavis** [comment]
Hey there!  Thanks for opening this issue.

The issue you're experiencing is unfortunately known.  Chrome has poor support for interacting with multiple profiles from the extensions API, and the result is that Tusk can really only support one account.

Issue #126 documents the problem of multiple browser profiles.  It looks like future versions of Chrome will support multiple profiles, but right now there's nothing I can do.

I'm going to close this issue as a duplicate since it is now tagged in #126.  If you feel that this is a different problem, feel free to reply and we can keep digging.

**Comment by kewlguy2** [comment]
Brandon, Thank you for pointing out this could be a duplicate issue.

I am finding I am getting kicked/need to login in the latest firefox beta
too.

I have previously gotten into the habit of using both multiple browsers AND
multiple chrome persona(s) to keep my businesse(s) info separate and
keepass worked well until Google stopped allowing me to use it for
"crossbrowser" password database storage.

Currently I am finding I may need to submit my issue directly to
keepass.info as my databases are no longer staying in sync using Google
Drive on such a diverse group of devices & browsers.

The database, stored in my personal Drive, that my mobile uses is falling
behind on changes made from desktops even if I completely log out of the
current mobile app including locking the database.

I just opened my google drive database on both Ubuntu and Windows and there
is the entry I am looking for yet it refuses to sync up fully to give me
the entry on both of my Android mobiles.

You can see in the pictures the folder & entry are missing on my mobile
from an entry that was saved on my Windows desktop that my Ubuntu machine
can see.

Regards,

Don Moody
1(780)707-5558
www.handymanreality.com

NOTE: I discovered that the BEST place to put ratings for businesses where
one can be easily added, on mobile, is through the Google maps by entering
"Handyman Reality Edmonton" and then swiping up from the bottom to select a
star rating.
