### ISSUE TITLE
Pcloud support?

### ISSUE THREAD

**Issue by chrisgsadler** [subdavis/Tusk#145]
## This issue is a 

- [x] bug
- [X] question
- [ ] feature

### Please describe the current behavior, and explain why it's bad.

I can seen on the web page that pcloud is supposed to be supported, and I can find reference to it in the source code, but I cannot find a way to configure it.
How do I set it up?
My version is 2018.2.25 - firefox extension

otherwise, great extension!

**Comment by subdavis** [comment]
Hasn't been published to the extension store yet.  I updated the website intending to test and publish that day, but got terribly busy with some personal tasks.  This is coming soon, but I'll leave this issue open until it gets fully published.

Sorry for the delay

**Comment by chrisgsadler** [comment]
no worries!
thanks for letting me know
looking forward to seeing it!

cheers,
--
  Chris Sadler
  chris_sadler@sent.com



On Sat, Apr 28, 2018, at 10:41, Brandon Davis wrote:
> Hasn't been published to the extension store yet.  I updated the
> website intending to test and publish that day, but got terribly busy
> with some personal tasks.  This is coming soon, but I'll leave this
> issue open until it gets fully published.> Sorry for the delay


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/subdavis/Tusk/issues/145#issuecomment-385126068

**Comment by subdavis** [comment]
Update: Published to firefox addon store.  Going to test it with the smaller pool of FF users for a few days, then release on chrome.

I'm not so worried about the PCloud part, but it comes bundled with an update that removes JQuery in favor of some native JS functions I wrote and I'm being cautions.
