### ISSUE TITLE
Firefox 59 on Ubuntu 18.04 can not connect to DropBox

### ISSUE THREAD

**Issue by kcwms** [subdavis/Tusk#147]
## This issue is a 

- [X ] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Ubuntu 18.04 LTS minimal install
FireFox 59.0.2 (64-bit)

After selecting DropBox, I'm sent to the [DropBox authorization page](https://www.dropbox.com/oauth2/authorize?response_type=token&force_reapprove=false&client_id=lau0eigo4cfthqz&state=n8TifyjnU6%2FcWk2zoLHkbw%3D%3D&redirect_uri=https%3A%2F%2Fc39d32dc24a3f8b94e8a48b6833ae68d733b4a92.extensions.allizom.org%2Fdropbox) and I select the Allow button

I'm then presented with a Firefox error 
**Your connection is not secure and this message
The owner of c39d32dc24a3f8b94e8a48b6833ae68d733b4a92.extensions.allizom.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.**

In my dropbox account it shows that KeePass Turk is a connected app

This works perfectly fine in Chrome Version 66.0.3359.139 (Official Build) (64-bit) on the same machine
This also works fine in both Firefox and Chrome on Xubuntu 18.04

### Please describe how you think it should change.

Tusk should connect to DropBox and work as advertised

**Comment by subdavis** [comment]
Hey there.  Thanks for the bug report.  I am unable to reproduce this issue with ubuntu, dropbox, and firefox 59.  

That being said, navigating to the dropbox auth link manually does produce this error.  In a normal browser window, I see the error you described.  In the WebAuthFlow popup, everything works as expected.  

The redirect to  c39d32dc24a3f8b94e8a48b6833ae68d733b4a92.extensions.allizom.org is some hackery for passing the dropbox oauth credentials back to your browser.

Please try to clear your cache, remove KeePass tusk as a connected app from the dropbox settings console, reinstall Tusk, and try again.

Are there any special settings or extensions you've configured with firefox that might be getting in the way here, or are you able to reproduce this on a clean install of FF59?

**Comment by kcwms** [comment]
>>Hey there. Thanks for the bug report. I am unable to reproduce this issue with ubuntu, dropbox, and firefox 59.
Please try to clear your cache, remove KeePass tusk as a connected app from the dropbox settings console, reinstall Tusk, and try again.

After doing that, Tusk get's added as a connected app on DropBox and I no longer see the error page from FireFox. You can close this bug.

>>Are there any special settings or extensions you've configured with firefox that might be getting in the way here, or are you able to reproduce this on a clean install of FF59?

This was only the second change I made to a clean install of Ubuntu 18.04 (which installs Firefox by default).  The only other add-on I have is Privacy Badger. I was logged into Firefox sync.

Thanks.
Once  [Does not work on ubuntu 18.04 and firefox 59 #146](https://github.com/subdavis/Tusk/issues/146) gets resolved, I can uninstall Chrome.
