### ISSUE TITLE
[FEATURE REQUEST] Add support for Mega.co.nz & Box.com

### ISSUE THREAD

**Issue by NoX1De** [subdavis/Tusk#153]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

I'm assuming that since your example here is literally the feature request I was going to suggest (lol) that this isn't the first time you've heard a request to add support for Mega.co.nz...however, I didn't see an issue open for it so I wanted to submit one.  This would be really awesome if you added support for Mega.  I would also love to see support for using Box.com cloud storage as well.

Thank you!

**Comment by subdavis** [comment]
I've been waiting almost 6 months for someone to ask this.  

The answer is: Mega.nz has no developer API.  There is simply no way to interact with Mega programmatically from a browser.

#94 tracks Box.com support which I intend to add soonish.

Thanks for finally asking.

**Comment by NoX1De** [comment]
Lol, that is hilarious- honestly, I was expecting this type of response (that it's not currently possible to add Mega support...argh.) in a way I can see why they might have decided to not create a developer API, but still unfortunate.  Glad to hear that Box.com is coming soon(ish)!

**Comment by subdavis** [comment]
Closed due to #94
