### ISSUE TITLE
[Suggestion] Navigate between entries in reverse

### ISSUE THREAD

**Issue by rEnr3n** [subdavis/Tusk#159]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

The current hotkeys for navigating entries are `Tab` and `Down` keys. 

### Please describe how you think it should change.

Please consider adding `Shift+Tab` and `Up` keys to navigate the entries in reverse order.

**Comment by subdavis** [comment]
Seems completely reasonable.  This will come in the next release.

**Comment by subdavis** [comment]
Solved in #173
