### ISSUE TITLE
[Suggestion] Add keyboard shortcuts for copying entries

### ISSUE THREAD

**Issue by rEnr3n** [subdavis/Tusk#161]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

I cannot copy the password using keyboard. I have to use my mouse to do so.

### Please describe how you think it should change.

Please add support for using keyboard shortcut for copying the password (e.g. `Ctrl+C`). I want to be able to copy the username as well (e.g. `Ctrl+B`).

**Comment by subdavis** [comment]
Excellent suggestion.  I'll see about adding these for an upcoming release
