### ISSUE TITLE
Support to mask/unmask master password input field

### ISSUE THREAD

**Issue by realprogrammer** [subdavis/Tusk#162]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
Currently a user cannot see and correct his entered passphrase. Sometimes it is really a pain to enter complicated passphrase.

### Please describe how you think it should change.
I would find it helpful if the input field could be masked/unmasked with a button.
 
### Anything else?
I've implemented this feature in the following branch: https://github.com/realprogrammer/Tusk/tree/feature/unmask

I would be pleased about your opinion and feedback!

**Comment by zmilonas** [comment]
Maybe create a PR for that?

**Comment by subdavis** [comment]
Thanks @realprogrammer 

I'd like to echo Zachary and ask that you open a pull request so that all participants could review and potentially merge your changes.  Thanks for your interest in the project.

**Comment by zmilonas** [comment]
@subdavis can we reopen since the revert because of a security bug?
