### ISSUE TITLE
Hotkey doesn't work

### ISSUE THREAD

**Issue by arkaydeus** [subdavis/Tusk#170]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behaviour, and explain why it's bad.

I have the latest version of Chrome on win 10 64. That's chrome 66. Tusk works fine but the CTRL+SHIFT+SPACE hotkey has never worked, despite being turned on. The only way I can access Tusk is with the mouse.

Thanks

**Comment by subdavis** [comment]
This has been solved already in #163

It hasn't been released to the webstore yet.  Should be published soon.  Thanks.
