### ISSUE TITLE
[Suggestion] SFTP support

### ISSUE THREAD

**Issue by conradludgate** [subdavis/Tusk#172]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Keepass databases cannot be accessed directly via SFTP.

### Please describe how you think it should change.

Add support for SFTP. The npm package ssh2 seems to be popular and supports SFTP.

### Anything else?

It's supported by Keepass2Android and in the Keepass desktop client through SftpSync, it would be nice to have it on Tusk too.

**Comment by subdavis** [comment]
Sure, that seems like a reasonable request.

**Comment by subdavis** [comment]
Cc @graille

Wait a second.  SFTP is a totally different protocol than HTTP.

Browsers have no support for native socket connections.  The library you cited requires the socket API that only exists in the Node.js runtime.

This feature cannot, as far as I am aware, possibly exist.  It's the same reason you can't open an SSH session from a browser.

Closing as wontfix.
