### ISSUE TITLE
[Suggestion] Show the name of group of items

### ISSUE THREAD

**Issue by jeferro** [subdavis/Tusk#174]
Hello,

First of all, congratulations for your plugin. I open this issue for a potential improvement. I would like the plugin will show the name of the group of the items when it shows them. For example, in my database, I organize my password in groups (I have groups within groups), and I have 2 or more account for the same site. So, if the plugin show the name of the group of each item, I can discriminate the items.

**Comment by zmilonas** [comment]
Hi, 

Thank You for the suggestion. I think this is a duplicate of #90. And as per that issue this feature is planned :)
If You think above mentioned issue does not reflect your suggestion please do not hesitate to keep your issue open and maybe further clarify the differences.
If it's duplicate then consider closing Your issue and discuss in #90

**Comment by jeferro** [comment]
Thank you for your response. I close this issue and I will comment in the feature #90.
