### ISSUE TITLE
Add support for OneDrive for Business

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [subdavis/Tusk#175]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

No support for OneDrive for Business. I can't use the regular OneDrive or one of the other cloud storage options (company policy).

### Please describe how you think it should change.

Please add support for Onedrive for Business.

**Comment by zmilonas** [comment]
Could you please post what type of error message do you get when you try to login with OneDrive option?

Or maybe steps to reproduce?

**Comment by Jaap-van-Hengstum** [comment]
I get the login page for the regular OneDrive, but I can't login here with my OneDrive for Business account. The signin page for OneDrive for Business is on the Office 365 site (https://www.office.com).

As far as I understand, OneDrive for Business is a different service from the regular (consumer) OneDrive. 
As explained [here](https://support.office.com/en-us/article/what-is-onedrive-for-business-187f90af-056f-47c0-9656-cc0ddca7fdc2):

> OneDrive for Business is the Microsoft cloud storage service that comes with Office 365 or SharePoint Server. With OneDrive, you can securely store all your files in one place, share them with others, and get to them from anywhere.
>
> OneDrive is the Microsoft cloud service that lets you securely store all your files, share them with others, and get to them from anywhere. When you use OneDrive to store work or school files, it's sometimes called OneDrive for Business.

It seems that the [OneDrive REST API](https://docs.microsoft.com/en-us/onedrive/developer/) can be used for both the regular OneDrive and OneDrive for Business.

**Comment by zmilonas** [comment]
Thank you @Jaap-van-Hengstum .

That's why I'm confused. From what I gather the API is the same. From my limited knowledge about OneDrive for business - You have a company Office 365 account, right? What happens when you try  to log in with your credentials (company email and password) on the login.live.com sign in page? Do you get "Wrong password"? Or anything else?

**Comment by subdavis** [comment]
Great.  Looks like 365 supports oAuth, just through a different portal than the regular Microsoft accounts...

https://docs.microsoft.com/en-us/outlook/rest/get-started

Need to create a new application in the azure management portal.  Looks simple enough.  

The tricky part may be testing it.  I don't have access to a business account.  I may need to sign up for office 365...

**Comment by zmilonas** [comment]
We can actually cooperate on that @subdavis.
I have an access to one or two Office 365 accounts that I can use for testing no problem.
Great that you actually found the place they hid the difference between personal live and o365

**Comment by Jaap-van-Hengstum** [comment]
@zmilonas I get the following error message trying to sign in:
> That Microsoft account doesn't exist. Enter a different account or get a new one.

But judging from the discussion above, I guess you already figured that out.

**Comment by subdavis** [comment]
After some research, I don't believe I'll be able to do this.  I can do my part, but Tusk would also have to be registered by the system administrator for your business account.  Your administrator controls what applications are granted access to your account and data, and Tusk would need to be registered there.

**Comment by Speed1** [comment]
If I remember correctly Tusk don't have to been registered from your System Administrator. Your System Administrator has to activate only the possibility for the users to allow users to allow third party apps to access their data
![adminconsent](https://user-images.githubusercontent.com/11215021/54819693-fd500600-4c9c-11e9-9e0b-51894e259232.jpg)

You need the Adminstrator approve only when you ask for too much data. (actually I cannot find the Microsoft Doc)

I would love to see this feature and if you need some testing let me know.

Thx :)
