### ISSUE TITLE
Error: Invalid response: 405 Method Not Allowed

### ISSUE THREAD

**Issue by Tiger862000** [subdavis/Tusk#176]
Hi,

## This issue is a bug using Tusk in conjunction with Nextcloud on a home server.
- [x ] bug
- [ ] feature
- [ ] question
### Please describe the current behavior, and explain why it's bad.
Sharing the URL / link
After entering the Webdav link in Tusk settings inlcuding predefined password and username
Tusk shows this error message in settings "Error: Invalid response: 405 Method Not Allowed"
Tusk would not prompt me with the input field for my master password.
No access to database

### Please describe how you think it should change.
Clear log messages and instructions on how to overcome the issue.

Thank you!

**Comment by subdavis** [comment]
Have you read https://github.com/subdavis/Tusk/wiki/WebDAV-Support ?

What is your webDAV link?  You can use "example.com" for the domain name if you don't wish to share your domain or IP

**Comment by Tiger862000** [comment]
Yes I red it. My Nextcloud instance is not security critical, so data is not too important on it.

My webDAV link looks like this: https://subdomain.duckdns.org/index.php/s/cblablablablalink

**Comment by subdavis** [comment]
I see your problem.  That's the full URL, not the base URL.

Try using just https://subdomain.duckdns.org/index.php without the path.  Tusk will scan your webDAV server and discover your KeePass database dynamically.

They must have a .kdbx extension.

**Comment by subdavis** [comment]
Closing with the caveat that documentation of this behavior should be better.
