### ISSUE TITLE
How do I filter Keepass entries on URL path, not just on domain?

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [subdavis/Tusk#177]
## This issue is a 

- [ ] bug
- [ ] feature
- [x] question

### Question

I have a lot of different development sites on my local computer:

http://localhost/SiteA/
http://localhost/SiteB/
http://localhost/SiteC/
etc.

I use the `TUSK_URLS` field to add these sites to the different Keepass entries, but I suspect that the Tusk dialog is only filtering on the domain part of the URL and not the path, because when I f.e. go to http://localhost/SiteA/login.html, I also see the Keepass entries for the other localhost sites.

Am I doing something wrong here, or is this a feature request?

**Comment by subdavis** [comment]
Your suspicion is correct, and this is a feature request.

However, I don't know of any other password manager that works like this -- they all filter based on origin, since that's the only security-relevant part of a URL.  

Do you have an example of a password manager that works like this?

**Comment by zmilonas** [comment]
closed in #195
