### ISSUE TITLE
Copying the username clears the clipboard

### ISSUE THREAD

**Issue by rEnr3n** [subdavis/Tusk#181]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Copying the username using the keyboard shortcut `Ctrl+b` does not copy the username. It clears the clipboard instead.

### Please describe how you think it should change.

`Ctrl+b` should be able to copy the username.

**Comment by zmilonas** [comment]
Fix prepared in #183
