### ISSUE TITLE
Navigation in reverse using Shift+Tab does not work

### ISSUE THREAD

**Issue by rEnr3n** [subdavis/Tusk#182]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

I can navigate the entries in reverse using `Up` key. However, `Shift+Tab` can't.

### Please describe how you think it should change.

`Shift+Tab` should be able to navigate in reverse as expected.

**Comment by zmilonas** [comment]
Fixed in #184
