### ISSUE TITLE
Tusk not recognising new credentials

### ISSUE THREAD

**Issue by HarryStottle** [subdavis/Tusk#185]
## This issue is a 

- [x] bug

### Please describe the current behavior, and explain why it's bad.

I'm a new user (only had it installed a week) but have used it pretty extensively in that week, without any problems - including performing the kind of update which has just failed. I'm the one who gave you a 5 star review last week https://addons.mozilla.org/en-US/firefox/addon/keepass-tusk/reviews/ (anon user dea6fa). Hadn't spotted this feedback option or I would have posted my questions here. 

Just added a new login to my kdbx (using Keepass). Saved it (within Keepass)

Opened firefox, opened the password file in Tusk, searched for the new login, not there. Checked Keepass and it was still there. Checked location of the file being used by Tusk, definitely the right file. Thought perhaps it might need me to log out of Keepass (which it hasn't previously but wanted to eliminate possibility). Exited Keepass. Closed browser. Reopened and reselected file in Tusk. Still not showing the new login. 

Rebooted windows. No difference. 

Can't think of any other way to force it to refresh itself! It is clearly reading some version of the file which doesn't match the actual current version. 

Suggestions?

**Comment by subdavis** [comment]
So you're using the local file upload database source right?  Where you have to select the file from your filesystem?

Did you re-add the file in Tusk?  As documented, the database file doesn't refresh automatically.  You must re-add the file when you make changes.  This is why you have to agree to the warning when you enable that feature.

If you're not sure what I mean, try disabling and re-enabling the toggle for local password file in settings, and read the warning again.

If you've already done this, let me know And we can move on to other steps

**Comment by subdavis** [comment]
From reading your first post, it seems you've already done this.

Are you able to "save-as" a new file from KeePass, and open this new file in Tusk?  Can you completely remove the old file and add it back, or add the newly saved copy?

I'll re-test this feature when I get home.  Thanks.

**Comment by HarryStottle** [comment]
Clunky. 
These are the precise steps I had to take to force an update
1 Enter "manage databases" (option available before unlocking. After unlocking, use the Settings cog and "Cloud Storage Setup")
2 Scroll down to "File System" 
3 Disable
4 CLOSE BROWSER (otherwise the change is ignored)
5 Make changes in Keypass and Save them
6 Open Browser and go back to Manage Databaes
7 Re-enable "File System"
8 Re-select file

That works. Miss any of those steps and it doesn't.

The need for steps 3, 4 and 7 suggest that you're holding a copy of the kdbx file, once selected, PERMANENTLY. Why isn't it just released at the end of a session, then re-opened, when the user enters their credentials in the next session? 

That would automatically ensure that they capture any changes made in Keypass between sessions and eliminate the need for the steps above altogether.

**Comment by zmilonas** [comment]
I think that's why the file system support is bot recommended. There is little support for chrome interacting witht rhe locla user files. It's a security issue on chrome side. I recommend either using one of the cloud providers or using a KepassHttp tunnel with a standalone client.

**Comment by zmilonas** [comment]
Since we can't fix it. Can we close this @subdavis ?

**Comment by Neve** [comment]
is it possible to add 'sync' button, to help users who have local databases?
