### ISSUE TITLE
Failed to execute 'getRandomValues' on 'Crypto': The ArrayBufferView's byte length (1910365) exceeds the number of bytes of entropy available via this API (65536).

### ISSUE THREAD

**Issue by JonAnder83** [subdavis/Tusk#186]
## This issue is a 

- [X] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Failed to execute 'getRandomValues' on 'Crypto': The ArrayBufferView's byte length (1910365) exceeds the number of bytes of entropy available via this API (65536).

### Please describe how you think it should change.

I get this error trying to unlock my database.

### Anything else?

Well, I recently changed my database´s settings and are as follow: Encryption algorithm: AES 256 bit. Key Derivation Function: Argon2, Transform Rounds: 29, Memory Usage: 64Mb, Parallelism: 8 threads.

It's hosted on Google drive. I open it with KeepassXC and Keepass on windows. Tusk fails to open on either windows and linux. It also does work on Android with Keepass2Android

Happy to help solve this :)

**Comment by subdavis** [comment]
Wow, that's a lot of bytes.  I'll take a look and let you know if I have questions.  Thanks!

**Comment by zmilonas** [comment]
Wow. I thought it's something with the kdbx4 support but i got my test database with the same settings open in Tusk although it took around 15 seconds to decrypt. 

How many entries do you have? I have only two in the test database maybe that's why I can't reproduce/.

**Comment by JonAnder83** [comment]
Yeah, it was the version 4 format, I went back to version 3.x and it is working again.i can have around a hundred entries in the database. Let me know if you need more info

**Comment by JonAnder83** [comment]
How's it going? Need any testing?

**Comment by subdavis** [comment]
Progress is going to be slow on my end for a while.  Lot of other stuff going on right now.  Looks like the WASM argon2 module may need to be rewritten, which won't be a small task.

I'm not confident that an efficient argon2 implementation can be made for the web, but it may be a bit soon to make that call.

**Comment by subdavis** [comment]
Had the chance to dig into this a bit - it was a head scratcher, until I decided to add some large (>1MB) attachments to my keepass database and I was immediately able to reproduce.

Because of the way protected items are "salted" in memory, there's a bug in kdbxweb that comes from https://github.com/keeweb/kdbxweb/blob/a4d58631f2c98667e0de2f46915db2dd79bddd07/lib/crypto/protected-value.js#L45

I'll patch it over there and have Tusk fixed soonish.   Great catch!

**Comment by JonAnder83** [comment]
Glad I helped! :)
