### ISSUE TITLE
"No network connection"

### ISSUE THREAD

**Issue by scrubrug** [subdavis/Tusk#190]
## This issue is a 

- [X ] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Everytime I try to login to Tusk, I get a "no network connection" pink error box.  I have internet on the device and cannot figure out why it is doing this.  I installed Tusk on another computer and it works fine, for whatever reason on my laptop it will not work.  I connected the file from my google Drive and it says it's connected.  I uninstalled and reinstalled the Tusk addon with no success.  Any other ideas on how to fix this issue?

**Comment by zmilonas** [comment]
Hey @scrubrug thanks for using Tusk and reporting a bug. I'll be glad to try and help you.

Can You please provide a little bit more detail? What browser and operating system are You using on both of these? We need to find what's different about Your configuration to be able to reproduce this bug or find the cause?

**Comment by subdavis** [comment]
No details from reporter.  Closing stale issue.  Feel free to reopen with additional information.
