### ISSUE TITLE
Logo Proposal to TUSK

### ISSUE THREAD

**Issue by ggabogarcia** [subdavis/Tusk#198]
Hello, I am a graphic designer and I am interested in the open source community. Your repository is great and I would like to collaborate with you designing a new logo for your extension :). I will respect your original design.

**Comment by subdavis** [comment]
Hey there!  I agree that Tusk could definitely use a new logo.  Thanks for your interest in helping out - lots of open source projects need help outside of just software work.

Let me know what you have in mind and maybe we can get the brand looking a little better!  All credit would of course be given to you on the README and website.

**Comment by ggabogarcia** [comment]
Hello sir, here I present my proposals for your extension Tusk, I hope you like it. As I said, I respected his current design.

![tusk](https://user-images.githubusercontent.com/35750428/43610358-74df4b9c-966b-11e8-908c-511aceeb63a2.png)

**Comment by subdavis** [comment]
@ggabogarcia WOW, I love these!  I especially love the side profile on the blue background - it's really an awesome looking logo. 

Thank you so much for putting this together.  I would like to replace the current logo with the top profile image.

Let's talk about getting this into assets.  For use inside the app, an SVG would be preferred.  The webstore, firefox store, and various oAuth providers require specific sized of PNG or JPEG which I am happy to render myself from the SVG.

 I would prefer that the copyright for all images in tusk be [creative-commons sharealike 4.0](https://creativecommons.org/licenses/by-sa/4.0/).  You can issue the assets to me under your own creative commons license, and I can "redistribute" them here.

**Comment by ggabogarcia** [comment]
Wow that's cool! Of course, I would like to know the sizes in which you need them to prepare the files. :)

**Comment by zmilonas** [comment]
I would also like to chip in and say that I'm really impressed with the work :) Looks great!

**Comment by ggabogarcia** [comment]
This would be the license I work with :) There should be no disadvantages :)

![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by subdavis** [comment]
Woohoo! 

I'll need 16,38,48,64,128, and 256 for various places around the web.  

We can also talk about attribution!  Is there a particular website, name, or phrase you'd like?  Something like "logo design by ggabogarcia" that links back to you?

Tusk is getting close to 10,000 users so I want to make sure folks know this is your work :)

**Comment by subdavis** [comment]
Logo has been added to application.  Still needs to go on the website.
