### ISSUE TITLE
Feature Request: Support for Nextcloud & Owncloud Shared URL's with Password Protection

### ISSUE THREAD

**Issue by sunjam** [subdavis/Tusk#223]
Owncloud and Nextcloud allow an optional password to be added to **Shared Links** before they can be accessed.  Tusk does not currently support these passwords, but it would add an extra layer of security to support them on shared URL's.  Thanks!

[Here is documentation on the OCS Share API, if it helps](https://docs.nextcloud.com/server/13/developer_manual/core/ocs-share-api.html).

**Comment by zmilonas** [comment]
Hey @sunjam thanks for the feature request.

I took a look at password protected ownCloud and Nextcloud links and seems like it's a custom password form implementation for both ownCloud and Nextcloud.

The link you provided does not lead to anything about the link retrieval, it's an API for adding and removing such shares - it is virtually impossible to programmatically access without an API for direct file retrieval.

I recommend using WebDAV with ownCloud and Nextcloud instead :)
