### ISSUE TITLE
Regression testing latest develop

### ISSUE THREAD

**Issue by subdavis** [subdavis/Tusk#232]
### This issue is a 

meta

## Requirement

Regression test latest develop branch for upcoming release.  There are a lot of features and fixes rolled up in here.  Appreciate help from any current contributors, especially @zmilonas

**Comment by zmilonas** [comment]
minor - ui/ux
![image](https://user-images.githubusercontent.com/25948390/45258426-849bf300-b3b7-11e8-8e89-c4e252c7526c.png)

Errors don't fall into labels

**Comment by zmilonas** [comment]
after denying permission request or a prompt in database management tab the slider still slides to on and a popup is opened.
![image](https://user-images.githubusercontent.com/25948390/45258436-a9906600-b3b7-11e8-8cb3-c852b886bc3f.png)

**Comment by zmilonas** [comment]
Posting here at the moment, will turn into issues later

**Comment by subdavis** [comment]
Awesome, TY
