### ISSUE TITLE
New feature: HMAC-SHA1 Challenge-Response functionality

### ISSUE THREAD

**Issue by wolffx86** [subdavis/Tusk#244]
### This issue is a 

feature

### Steps to reproduce - current behaviour
unlock database

### What is the expected behaviour
unlock database with extra security
 

#### Additional remarks
requesting functionality be added to be able to unlock KeePassXC DB with HMAC-SHA1 Challenge-Response functionality
 

#### Environment 
Chrome browser extension
**Operating System:**
any
**Browser:**
Chrome
**Storage:**
N\A

**Comment by zmilonas** [comment]
Please correct me if I'm wrong - isn't this feature request a duplicate of #69?

**Comment by subdavis** [comment]
Conversation on this topic should be moved to #69
