### ISSUE TITLE
URL autofill

### ISSUE THREAD

**Issue by fmunch** [subdavis/Tusk#246]
### This issue is a

feature

### Steps to reproduce - current behaviour

1. Focus the Omnibox.
2. Hit Ctrl+Shift+Space.
3. Select an entry containing a URL and press Enter.
4. If the currently displayed page contains a form it will be autofilled, else nothing happens.

### What is the expected behaviour

It might not be possible, but it would be great to fill the Omnibox with the URL contained in the entry.

#### Environment 

**Operating System:** Windows 10 Home 64 bits

**Browser:** Chrome 71.0.3554.4 64 bits

**Storage:** WebDAV (Nextcloud)

**Comment by zmilonas** [comment]
We can go to a URL when you choose but we cannot autofill omnibox.
For secutiry reasons chrome extensions cannot interact with chrome omnibox they can only be called by omnibox.

If you want a redirect when you choose an entry you can open another issue.
