### ISSUE TITLE
HMAC-SHA1 Challenge-Response functionality

### ISSUE THREAD

**Issue by wolffx86** [subdavis/Tusk#251]
### This issue is a 

feature

### Steps to reproduce - current behaviour
unlock database

### What is the expected behaviour
unlock database with extra security
 

#### Additional remarks
requesting functionality be added to be able to unlock KeePassXC DB with HMAC-SHA1 Challenge-Response functionality, specifically with Argon2 KDBX 4 type DB

How about NOT closing the issue before it is resolved or before i even get to followup on subdavis' question, zmilonas? That would be fantastic. You're just making more work for everyone, including yourself.

"What mechanism do you want to use for HMAC CR, @wolffx86 ?" I am referring to Yubikey and others like the Titan device by Google.
 

#### Environment 
Chrome browser extension
**Operating System:**
any, specifically ChromeOS cause i use a chromebook
**Browser:**
Chrome
**Storage:**
N\A

**Comment by subdavis** [comment]
1. There was no need to open another issue.  You could have just replied to the closed issue.
2. Chill.  @zmilonas was just trying to keep our paperwork in order.

> I am referring to Yubikey and others like the Titan device by Google.

3. Then zach was right -- this is a duplicate of #69.  Feel free to upvote that issue to show support or reply if you're interested in supporting the Titan protocol.  We really _did_ already have an issue for that.

I appreciate you participating and talking about new features.  Keep in mind this is free software that people build in their spare time.
