### ISSUE TITLE
Create seperate ISSUE_TEMPLATEs for different types of issues.

### ISSUE THREAD

**Issue by zmilonas** [subdavis/Tusk#253]
meta

1. update `ISSUE_TEMPLATE`s to have two/three for feature requests/bugs/questions
1. Completly abandon checklist format for issue type - really confusing in snippets

**Comment by subdavis** [comment]
Yessssss

**Comment by zmilonas** [comment]
![image](https://user-images.githubusercontent.com/25948390/45957013-4851cf00-c014-11e8-8917-757ce5b83de6.png)
