### ISSUE TITLE
Tusk loses memory in current Firefox

### ISSUE THREAD

**Issue by HarryStottle** [subdavis/Tusk#257]
### Steps to reproduce - current behaviour
sign in as normal

generally (but not always) everything works as normal, perhaps for the first site I need to login to. Then I go to a second site and find
a) the Keepass database is no longer unlocked
b) Tusk has forgotten that I'm using a keyfile
c) Tusk has also forgotten that it's set to exit when I close the browser.

This behaviour started a couple of weeks ago with the update to Firefox 68 and continues in 68.02 

In Iron, (Chrome engine) Tusk continues to work as normal

I have to point out that what is happening now, in Firefox, is an accelerated version of a very occasional twitch I first observed a few months back but never got around to raising as an issue because it was much less severe. At that time, I would occasionally find I'd have to login twice before Tusk would stay active. It was so rare that I usually thought I'd failed to login the first time - till I started monitoring it more closely. Even then it was sufficiently rare (< 1 a week) that I didn't care. And, on those rare occasions, it didn't also forget everything else; so I wasn't forced to reset the keyfile or the exit behaviour. Now it's become routine, to the point where it's essentially unusable in Firefox. 

As no one else seems to be screaming about it, I'm guessing it must be some weird config issue within my own Firefox but I have no idea how to troubleshoot it.

#### Environment 

W10pro 1703 (64 bit)
Browser: see above
Storage: not relevant

**Comment by mishley** [comment]
Hello! GREAT addon. I can confirm that I'm also having this issue. I can reproduce it 100% of the time with the following use-case.
1. Open a site you use Tusk to fill creds (I'm not even sure if this is necessary).
2. Auth to Tusk (I use Dropbox for database and key file + password), slider set to 30 mins.
3. Don't use auto fill or anything, just click off of Tusk to cause window to close.
4. If you immediately re-open Tusk, it has lost track of the fact that you have authenticated (in spite of slider), it also appears unable to use the key file you've previously defined, and which you can still see in your configuration.
5. After a few minutes (3-5?) Tusk will "remember" you have auth'd and start working again, as normal.
6. You should be able to immediately reproduce however using steps 1-4 again.

Environment
Ubuntu Gnome 16.04 LTS
Firefox 62.0.2 (64-bit)
Tusk 2018.9.23

**Comment by HarryStottle** [comment]
Damn! I thought I'd noticed that secondary behaviour myself (step 5) but I thought I must have imagined it (and forgotten that I'd logged in again) but it happened just a couple of hours ago after the last "forget" behaviour, which had irritated me enough to post here. By the time I'd finished posting, tusk had "remembered" again!

**Comment by subdavis** [comment]
Thanks to both of you for these detailed reports!  I'm going to try and reproduce and get back to you if I have more questions.

**Comment by mishley** [comment]
@HarryStottle heh, well, I was relieved to come here and find your bug report, it made it easier for me to add what I had observed.

@subdavis no problem, thanks for the great extension! I just did some more testing and these two statements appear to be true, as well.
- The time limit for Tusk to "reset" or "remember" your login is almost exactly 1 minute, tested a few times with a stopwatch to be sure.
- Interaction with the Tusk UI via the button appears to reset that 1 minute timer.

**Comment by zyphlar** [comment]
Can confirm this problem in Firefox Developer Edition 63.0b9 (64-bit) on Ubuntu -- newly upgraded to 18.04 (had to install that ibus fix to let Tusk even stay open for more than a split-second). I'm only experiencing problem "A" however.

**Comment by HarryStottle** [comment]
further to Mishley's revelation, I haven't timed it as precisely but when I logged in this morning and found I couldn't use Tusk, I left the tab open and went about my other browsing business. Checked back about 5 mins later and surenuff, Tusk had woken up and was back to normal...

**Comment by HarryStottle** [comment]
Yup, clear pattern emerging. 

30 mins after writing the above, went to login to something else and, again, Tusk had gone "offline". Left it for a couple of minutes and it was back on.  Ten mins later came here to add this comment and same again. Couldn't login to github for just under 2 mins...

**Comment by zyphlar** [comment]
Same here. Problem mysteriously vanished after having done nothing much to fix it shortly after my previous message.

**Comment by zmilonas** [comment]
@mishley thanks for you eagerness to contribute! I'm not sure if you understood correctly. It's about creating a User Acceptance Test case. It's in puppeeter. It's still not in `develop` branch. If you're so inclined you can checkout the `feature/puppeeter` branch and there in `tests/integration/integration.js` an example test is written.
https://github.com/subdavis/Tusk/blob/feature/puppeteer/tests/integration/integration.js

**Comment by subdavis** [comment]
This was the dumbest bug.  It really demonstrates how the code organization of this project needs... work...

Thank you both for your fantastic bug reports.

**Comment by HarryStottle** [comment]
just confirming the fix worked.
Nice one. Sorted.
