### ISSUE TITLE
Hide entries that have been deleted

### ISSUE THREAD

**Issue by CodeAlDente** [subdavis/Tusk#261]
At the moment Tusk is even showing entries that have been deleted (moved to trash in KeePass). I do not consider this as a bug as it could be useful to some people to check their login details from the past for different reason. But I do believe that most of us are interested in active logins, those entries that have not been deleted. So, it would be awesome to have an **option to show all entries or to hide entries that have been deleted**.

**Comment by subdavis** [comment]
Sure, seems reasonable.

Probably stroke through and de-prioritize in search? I don't know if outright removal is the best thing to do.

**Comment by CodeAlDente** [comment]
That would be a good option.

But I have just discovered that logins that have expired (set in KeePass) get already stroke through.
Why not hiding those deleted entries with the option to show them and - to remember this choice - so that they will be shown in the future as well?

Yet they need to look different from the entries that have been expired. Maybe those deleted entries should get stroke through (when shown) and those expired should be in red color?

**Comment by zmilonas** [comment]
AFAIK Trash is kind of like any other folder in KeePass database or is it more standardized? If it isn't we would have to much it by name which is kind of flaky IMO.

**Comment by swartzja** [comment]
I would take a slightly different approach. There's really no such thing as a "deleted" entry, the action simply moves the entry to a group named Recycle Bin that has both Behaviors (Auto-Type and Searching) set to Disabled. I create subgroups called "closed" or "archived" for accounts that I don't use, but want to keep record of. I mimic the Recycle Bin by setting set the Behaviors to Disabled. To be functionally consistent and make Tusk function like the KeePass application, I think ignoring entries in groups that have the Searching Behavior set to Disabled is the way to go.

**Comment by subdavis** [comment]
Super agree with that.  Great idea, @swartzja

**Comment by rspier** [comment]
It looks like this has already been attempted:

https://github.com/subdavis/Tusk/blob/develop/services/keepassService.js#L168
				// Entry properties defined by the parent group
				entry.searchable = true;
				if (group.enableSearching == 'false') //verify
					entry.searchable = false;


But it looks like group.enableSearching isn't being properly set (at least in my primary kdbx.)
