### ISSUE TITLE
First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by bweather04** [subdavis/Tusk#262]
Hello.
Getting this error tonight?
First argument to DataView constructor must be an ArrayBuffer at the top of the extension once you enter your master password.
V2018.9.27

Thank you.
![screenshot 2018-10-03 at 9 33 28 pm](https://user-images.githubusercontent.com/25751289/46453205-17c90e00-c755-11e8-9f97-2e53e745d31f.png)

#### Environment 

**Operating System:**

**Browser vendor and version:**

**Storage Provider:**

**Comment by zmilonas** [comment]
Duplicate of #224

**Comment by subdavis** [comment]
If you aren't going to tell us the OS or storage provider, why even bother opening this issue?
