### ISSUE TITLE
Incorporate opt-in or opt-out crash and usage analytics

### ISSUE THREAD

**Issue by zmilonas** [subdavis/Tusk#264]
I'm wondering if there is a way for the extension to collect anonymous usage analytics so we could understand which features are used and maybe what's still not clear. That'd be great for UX but might be not appealing for privacy advocates. Looking for community feedback

**Comment by subdavis** [comment]
The community would roast us.  I've spent a lot of time in /r/KeePass and they're completely unreasonable about this sort of thing.  They don't even like being asked to send analytics after a crash.  /R/privacytoolsio is even worse.

I would only be willing to do this if it were opt-in and we hosted the backend and open sourced the code.

**Comment by zmilonas** [comment]
Ok I'll close it for now. 

Probably out of scope until we deal with basic usage issues
