### ISSUE TITLE
Needs to reauthorize against google on each Firefox session

### ISSUE THREAD

**Issue by karlos1337** [subdavis/Tusk#275]
I'm using tusk in both Firefox and Chrome browsers, in Chrome all goes smooth but in Firefox I need to reauthorize my google account to access to my keys db (hosted in my GDrive) on each browser session and that don't occurs with Chrome.

Firefox: 63.0.3 (64bits)
OS: Antergos (Arch Linux)

**Comment by subdavis** [comment]
And I assume you have more than 1 Google account on that browser?

**Comment by subdavis** [comment]
Either way, definitely a duplicate of #133
