### ISSUE TITLE
Error message during app registration with pCloud

### ISSUE THREAD

**Issue by alensiljak** [subdavis/Tusk#276]
### Steps to reproduce - current behaviour

1. install Firefox addon
2. enable pCloud provider
3. click Allow app in the next screen

### What is the expected behaviour

Enable the provider.

#### Additional remarks

![image](https://user-images.githubusercontent.com/462445/49147963-5e2a8b80-f306-11e8-8b6c-9721ffb624ea.png)

#### Environment 

**Operating System:** Windows 10

**Browser vendor and version:** Firefox Developer Version, 64.0b12, 64-bit

**Storage Provider:** pCloud

**Comment by subdavis** [comment]
You've edited all the context out of this screenshot.  I have no idea what this image is.

It's clearly not Tusk, because that logo doesn't show up anywhere.

What screenshot is this?

**Comment by MisterY** [comment]
The screenshot is the error message after a user performs the three fairly simple steps listed under "Steps to reproduce".

**Comment by MisterY** [comment]
Hm, after disabling/enabling the plugin and restarting the browser, I can see the provider enabled and the list of databases from pCloud in the settings.

**Comment by MisterY** [comment]
Now I'm getting 

![image](https://user-images.githubusercontent.com/462445/49153350-c6cd3480-f315-11e8-982a-b656476772ae.png)

when trying to log in but that's a separate issue, I guess. You can decide if the first reported error is worth investigating further.

**Comment by subdavis** [comment]
> The screenshot is the error message that appears after the user performs the three fairly simple steps listed under "Steps to reproduce".

Which is what?  I cannot reproduce this bug, so I'll need to spend time getting Firefox Dev edition set up.

Since I can't reproduce this, the steps you provided are not enough to tell me where the error comes from.

I'm glad it's working now.  Did this happen on a brand new installation, or have you been using pCloud for a while?

**Comment by MisterY** [comment]
This is the first installation of Tusk. I would say it is a part of app authentication. Could be an issues with pCloud APIs but I'm not sure how that part works.
It happened after authenticating with pClound and registering the application with pCloud.

**Comment by subdavis** [comment]
>  I would say it is a part of app authentication.

So it's a screenshot from the popup window that opens when you enable pCloud.  Awesome.  That could either be my fault or pCloud's, but I'll keep fiddling with it to see if I can reproduce it.
