### ISSUE TITLE
The Google Drive integration does not work in Opera.

### ISSUE THREAD

**Issue by edward-raven** [subdavis/Tusk#299]
### Steps to reproduce - current behaviour

1. Install [**Install Chrome Extensions**](https://addons.opera.com/en/extensions/details/install-chrome-extensions/) extension.
1. Install **Tusk** extension.
1. Open Tusk Setting -> Manage Databases page.
1. Switch _Google Drive_ on.
1. There is an `[object Object]` error on the page.

### What is the expected behaviour

The Google Drive integration works.

#### Additional remarks

The Opera browser defines the `chrome.identity.getAuthToken` function, but it throws an error "Function unsupported.". This behaviour is described [here](https://dev.opera.com/extensions/apis/).

#### Environment 

**Operating System:** Windows 8 / 10

**Browser vendor and version:** Opera 58.0.3135.65

**Storage Provider:** Google Drive

**Comment by Adasss** [comment]
Hi, where can I get the updated chrome extension ?

**Comment by edward-raven** [comment]
Hi, it's not released yet.
You may patch the `options.build.js` and `popup.build.js` files in the extension folder `%AppData%\Opera Software\Opera Stable\Extensions\fmhmiaejopepamlcjkncpgpdjichnecm\2018.9.27_0\build`. Here are the patched versions: [options.build.js.txt](https://github.com/subdavis/Tusk/files/3041651/options.build.js.txt), [popup.build.js.txt](https://github.com/subdavis/Tusk/files/3041652/popup.build.js.txt)

**Comment by Adasss** [comment]
Thank You. Witch those files its working now :)
