### ISSUE TITLE
Firefox: Shared URL provider doesn't work

### ISSUE THREAD

**Issue by henryptung** [subdavis/Tusk#307]
### Steps to reproduce - current behaviour

- Open Tusk
- Enable Shared URL provider, add a link
- Refresh
- **See entry name has been lost**
- Click Advanced
- See under Stored Data that **`sharedUrlList` contains one object with no properties**
- Click Tusk icon, open unnamed entry, **see undefined name**
- Try to enter password, **receive `n is undefined`  error**

### What is the expected behaviour

Shared URLs should work properly in Tusk.

#### Additional remarks

Guessing this might be related to differences between Firefox and Chrome in storage APIs, but AFAIK Firefox only promises to store [JSON-ifiable](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) values, which may not(?) include typed objects like `SharedUrl`.

The extension does work properly in Chrome, but the versions aren't a perfect match:

- Firefox: 2018.11.28
- Chrome: 2018.9.27

#### Environment 

**Operating System:** Arch Linux

**Browser vendor and version:** Firefox 66.0.2 (64-bit)

**Storage Provider:** Shared URL

**Comment by henryptung** [comment]
Update after some research - looks like it's related to some weird bug with Firefox's local storage? For some reason, saving objects and then fetching them back loses all properties.

Update 2: Yup, this seems to be related to Vue and the way it decorates objects for observation (i.e. when they're added to the `this.links` array). I'll put up a PR.

**Comment by paxet** [comment]
Same happens to me (shared link don't work) with latest version of Firefox.

Operating system: Arch Linux / Windows 10
Browser vendor and version: Firefox 66.0.2 (64 bit) on both

**Comment by janstuemmel** [comment]
Hi, same issue here.

Using webdav for the moment is working with nextcloud

**Comment by mishley** [comment]
+1 same issue, haven't tried WebDAV with Nextcloud as above but will give it a shot.

**Comment by mindobjects** [comment]
Hi,

Do you have any idea of when a fix will be available ?
Just try with latest Firefox beta 67 and it doesn't work.

Thanks for your work and reply.

**Comment by Edward70891** [comment]
Identical issue here.
