### ISSUE TITLE
Database file not found on Nextcloud WebDAV

### ISSUE THREAD

**Issue by casKd-dev** [subdavis/Tusk#310]
### Steps to reproduce - current behaviour
- Create App password on Nextcloud (2FA enabled account)
- Input all needed information in WebDAV fields
- Scan for files
- Nothing is found
### What is the expected behaviour
- File is found and usable

#### Additional remarks
I own the Nextcloud instance and i can clearly see a PROPFIND request of the path with a 207 response, Tusk doesn't give any errors and just remains blank without any password databases
It used to work before and the enviroment has not changed but the file was not discovered anymore.
Keepass2Android works also just fine
#### Environment 

**Operating System:**
Linux RXHome 5.0.7-arch1-1-ARCH #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019 x86_64 GNU/Linux (Client)
Linux fra-n0 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Server)
**Browser vendor and version:**
```
Vivaldi | 2.4.1488.26 (Official Build) snapshot (64-bit)
-- | --
Revision | 82ed5c925a961b4a67c8948d7f03220f912b577c
OS | Linux
JavaScript | V8 7.3.492.25
Flash | 999.999.999.999 /usr/lib/PepperFlash/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36 Vivaldi/2.4.1488.26
Command Line | /usr/bin/vivaldi-snapshot --flag-switches-begin --enable-features=ProactiveTabFreezeAndDiscard --flag-switches-end --save-page-as-mhtml
Executable Path | /opt/vivaldi-snapshot/vivaldi-snapshot
Profile Path | /home/caskd/.config/vivaldi-snapshot/Profile 1
Variations | d1cd70a5-70ea8f2
```

**Storage Provider:**
Nextcloud 15.0.7 (Stopped working at 15.0.5)
Latest stable docker image -> https://hub.docker.com/_/nextcloud

**Comment by zacklayton** [comment]
Having an identical issue with the same Docker image. In my case my Traefik labels are:

```
- "traefik.frontend.headers.STSSeconds=315360000"
- "traefik.frontend.headers.referrerPolicy=no-referrer"
- "traefik.frontend.redirect.regex=https://cloud.domain.org/.well-known/(card|cal)dav"
- "traefik.frontend.redirect.replacement=https://cloud.domain.org/remote.php/dav/"
```

**Comment by casKd-dev** [comment]
To add to the issue, the `webdavDirectoryMap` for the same server id is empty.

**Comment by casKd-dev** [comment]
#130 seems like a similar issue, closing
