### ISSUE TITLE
Ability to open "child databases"

### ISSUE THREAD

**Issue by cosyd** [subdavis/Tusk#312]
### A feature you'd like to see
The ability to add "child databases", which eases use of multiple keepass databases in the plugin. A child database is automatically opened when opening the "parent" database and its password is stored in the parent database. This functionality is already present in "Keepass2Android" and very useful. Ideally it could use the exact same mechanism.
https://github.com/PhilippC/keepass2android/issues/174

### Alternatives you've considered
Switching manually between keyfiles (however requiring to enter the passwords manually each time, remembering which credentials are stored where and what file is currently open).

### Additional remarks
Multiple keepass databases are a clean way to separate concerns, e.g. shared family / team passwords. Adding this feature allows doing this more comfortably.

**Comment by subdavis** [comment]
I think this is a good idea.

I'm unlikely to do it myself.  I'll leave this as help wanted.

**Comment by subdavis** [comment]
I would no longer accept a PR for this, it's out of scope for this tool.
