### ISSUE TITLE
Unable to login to onedrive - account don't exist

### ISSUE THREAD

**Issue by liquidblack1** [subdavis/Tusk#315]
I've been using keepass for a while with nextcloud and it has beed working flawlessly. Couple a days ago I've moved my files to onedrive business along with my keepass db. Since then I've been trying to connect tusk with my onedrive but without a luck. I'm just unable to login to my account and I'm getting an error: Account doesn't exit. But when I try to log in via my personal account everything works. Is there any way to fix this ? I really love using Tusk.

**Comment by BillWSY** [comment]
+1 Here

**Comment by subdavis** [comment]
Onedrive business isn't supported.
