### ISSUE TITLE
First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by sachabruttin** [subdavis/Tusk#316]
## Bug report
I get the messae :  First argument to DataView constructor must be an ArrayBuffer 

### Steps to reproduce - current behaviour
- Connected to a OneDrive database
- I open Tusk
- I input the password
- it doesn't unlock
- Get  "First argument to DataView constructor must be an ArrayBuffer"

### What is the expected behaviour
Database is unlocked

#### Environment 

**Operating System:** Windows 10

**Browser vendor and version:** Google Chrome 74

**Storage Provider:** OneDrive

**Comment by subdavis** [comment]
Duplicate of #224
