### ISSUE TITLE
Shared Link Not Working

### ISSUE THREAD

**Issue by mld-ger** [subdavis/Tusk#317]
### Steps to reproduce - current behaviour

See this gif for reproduction:

![May-21-2019 13-53-08](https://user-images.githubusercontent.com/5991815/58094126-34c12d00-7bd0-11e9-8890-b13681f6b8ac.gif)

### What is the expected behaviour

The database should be downloaded

#### Additional remarks

The download link is the direct link and has no additional protection

#### Environment 

**Operating System:** MacOS 10.14.4

**Browser vendor and version:** Firefox 10.14.4

**Storage Provider:** Nextcloud 15.0.7

**Comment by AlfonsoML** [comment]
I'm having the same problem on Windows 10 with both Chrome and Firefox, trying to use a direct link to a Dropbox file as suggested in https://github.com/subdavis/Tusk/issues/131#issuecomment-377945149

**Comment by aladds** [comment]
Can confirm that this is also an issue with Firefox 67.0.1 on Mac OS 10.14.5 and Tusk v2018.11.28

**Comment by subdavis** [comment]
Only Dropbox and OwnCloud are supported, as it says.

Nextcloud is not supported.
