### ISSUE TITLE
Password Quality Estimation

### ISSUE THREAD

**Issue by Riajyuu** [subdavis/Tusk#321]
### A feature you'd like to see

Password quality estimation progress bar in both generator and display form.

This is a good feature in KeePass generator but seems missing here.

### Additional remarks

![image](https://user-images.githubusercontent.com/16912240/59236990-01c6f380-8be8-11e9-8ed7-cc5806ddbe0c.png)

PS: you may learn algorithm [here](https://github.com/FoxAuth/FoxAuth/blob/master/src/scripts/QualityEstimation.js). If any question, simply [ask](mailto:lolipopplus@protonmail.com)

**Comment by subdavis** [comment]
Tusk has no password creation mechanism.  You can't update a password, so I don't see the point of showing strength.
