### ISSUE TITLE
Kiwi Web Browser

### ISSUE THREAD

**Issue by mekineer** [subdavis/Tusk#324]
Have it work with Kiwi Web Browser.  Everything works currently except Autofill, and the setting "Grant Permission on All Websites" does not stay on.

The way I currently use it, I go into the extension and it shows the username and password for the site, and I can copy the password to the clipboard.

Also would like the option to permanently unlock the database.

**Comment by subdavis** [comment]
Kiwi is not a common enough browser to be worth the time to maintain.
