### ISSUE TITLE
Autofill/Autotype Behaviour Improvements

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [subdavis/Tusk#325]
### Behaviour should match/improve upon Chromeipass
When a URL is matched, Tusk should autofill on page load; not force the user to go to the interface and select the entry it's already found.

If there is only one entry found, autofill. If there are more entries found, provide a select dropdown on the input so the user can select the profile they want (see Chromeipass for what this behaviour should look like).

Provide a right-click menu option to 'autofill from Keepass'.

Are you able to intercept Keepass's shortcut (Ctrl+Alt+A for example) and autofill based on URL instead of letting Keepass autofill based on window title? Often the names of the entries in my database don't match the window title and thus won't autofill. Or perhaps provide your own keyboard shortcut to execute autofill based on the above criteria?

**Comment by subdavis** [comment]
Please read the issue history before opening a new issue for heavily discussed topics.
