### ISSUE TITLE
Unable to save shared link database

### ISSUE THREAD

**Issue by martinschwinzerl** [subdavis/Tusk#326]
### Steps to reproduce - current behaviour
0) Enter the Tusk configuration page and switch to "Manage Databases"
1) Add a key database of shared link type (cf. screenshot1.png)
2) Leave the "Manage Databases" section, for example by switching to "Manage Keyfiles"
3) Switch back to the "Manage Databases" section. The database link and its associated data are now presented as an empty connection without name. (cf. screenshot2.png)
4) Clicking on the Tusk symbol in the firefox toolbar reveals that no database is available and leads right back to the configuration page (screenshot3.png)

I've verified this behaviour both on an existing and on a new installation of Tusk.

### What is the expected behaviour
Database link should, once configured, remain available and be usable

#### Additional remarks
What mystifies me is that I have an installation of Firefox on a different computer but also with *buntu 18.04 LTS and Firefox where Tusk does indeed work as expected. The main difference is that on that machine mozilla sync is not enabled. This may of course be also a coincidence.

#### Environment 
Kubuntu 18.04 LTS 64 Bit
Firefox 67.0.4 (64 Bit)
Tusk version 2018.11.28
The shared database link is provided by my nextcloud installation and uses the https:// protocoll

![screenshot1](https://user-images.githubusercontent.com/35835665/60704454-cb3d7980-9f04-11e9-8d30-5dc981a640b1.png)
![screenshot2](https://user-images.githubusercontent.com/35835665/60704456-cbd61000-9f04-11e9-8687-70cc69f96147.png)
![screenshot3](https://user-images.githubusercontent.com/35835665/60704458-cbd61000-9f04-11e9-9aa1-e199097ece72.png)

**Comment by dnsbob** [comment]
I have also seen this on two recent copies of Firefox on Linux Mint.  It previously worked, but now it fails.

**Comment by pelzvieh** [comment]
Same here on Firefox 69.0.1 (64 bit) for Mac OS. When trying to open the empty-name link resource, I get "n is undefined" with a red bar in the KeePass Tusk pop-up.
![Bildschirmfoto 2019-09-22 um 14 34 05](https://user-images.githubusercontent.com/6665390/65387302-609f1b80-dd46-11e9-8282-a298f00e04fe.png)
