### ISSUE TITLE
Scan button doesn't react for WebDav

### ISSUE THREAD

**Issue by Suncatcher** [subdavis/Tusk#330]
## Bug report
Scan button doesn't work for WebDav provider. Previously it worked.
Provider is Stack.nl
Address is https://XXXXX.stackstorage.com/remote.php/webdav/

### Steps to reproduce - current behaviour
Enter address as usual

#### Environment 

**Operating System:**
Win10
**Browser vendor and version:**
Chromium 75
**Storage Provider:**
WebDav

**Comment by Suncatcher** [comment]
It starts to fetch for a while but then again
![SharedScreenshot](https://user-images.githubusercontent.com/6388034/62407930-5e161600-b58e-11e9-929b-8fd83c7c4c6a.jpg)

**Comment by pelzvieh** [comment]
Here on Firefox 69.0.1 (Mac OS), the scan button does exactly nothing. Even with the full path of the keepass file given as URL, neither will the scan button work nor the file be available from the tusk drop down.

**Comment by subdavis** [comment]
Webdav provider has had significant updates.  Closing issue, please open another.
