### ISSUE TITLE
Tusk won't launch

### ISSUE THREAD

**Issue by DrunkDuckling** [subdavis/Tusk#336]
### Steps to reproduce - current behavior
1. Install Tusk using "Software"
2. Press Launch

### What is the expected behavior
1. It opens...

#### Additional remarks
Have tried reinstalling it both using snap and store. Nothing works
It does noting when i try to launch it. No response or anything. 

#### Environment 

**Operating System:**
Ubuntu 19.04

**Comment by subdavis** [comment]
Not sure what you installed, but it probably isn't Tusk.

Tusk is not available as a snap, and the word "Launch" isn't used anywhere related to Tusk.  This is a browser extension, not desktop software.
