### ISSUE TITLE
Problem using keyfile 4 kdbx

### ISSUE THREAD

**Issue by nealmibe** [subdavis/Tusk#337]
Hello Tusk-Team,

I'm experiencing problems using a version 4.kdbx file in Keepass Tusk for Chrome. 

The file is generated through an CSV-import via Keepass XC and saved as 4-kdbx file. This file can't be opened in Keepass Tusk for Chrome. But the same procedure with a 3.1-kdbx file works well. 

I attached two sample files (3.1-kdbx and 4-kdbx version) as a zip file:
[sample.zip](https://github.com/subdavis/Tusk/files/3586902/sample.zip)

I used the generic CSV file from the website auf Keepass: https://keepass.info/help/base/importexport.html

Both files are protected with the password '1234'. Both can be opened in Keepass XC.

Maybe you have an idea what could be the mistake? Thank you for your time.

Regards, 

Neal

**Comment by vii1** [comment]
New user to KeePass here. I have a v4 kbdx (w/ master password, no keyfile) and Tusk fails with "Incorrect password or keyfile". Might be this same problem?

**Comment by subdavis** [comment]
Need to look at upgrading Argon2 implementation, I have several databases that I can use to reproduce this.

**Comment by subdavis** [comment]
Upgraded to the newest version of argon2 wasm, confirmed kdbx4 is working.  I'd like to move this into a service worker, but that can be a separate issue.
