### ISSUE TITLE
Google drive error

### ISSUE THREAD

**Issue by quicknir** [subdavis/Tusk#338]
I just installed Tusk on Windows 10, Chrome: 77.0.3865.90 (Official Build) (64-bit) (cohort: Stable). When I try to turn on Google Drive under the Manage Databases tab, there's no dialogue asking me to approve access to google drive. Instead, a red box appears beside it with the text [object Object].

I still have CKP installed but I can't see why that would interfere with this issue or cause it. Happy to provide more details.

**Comment by subdavis** [comment]
Duplicate of #293
