### ISSUE TITLE
Cannot request origin permission for WebDAV server

### ISSUE THREAD

**Issue by oneffr** [subdavis/Tusk#351]
### Steps to reproduce - current behaviour

Dear Tuskanians,

unfortunately, I ran into a problem with Tusk version 2024.8.2.

When I try to add a new WebDAV database under "Manage Databases" -> "WebDAV" I get the following error message instead of being presented with a selection of databases like in the previous versions:

"Error: Cannot request origin permission for https://\<SERVER>:\<PORT>/\<PATH>' since it was not declared in the manifest".

### What is the expected behaviour

 

After clicking "Add Server" I expect to see a list of keepass databases found by Tusk under the entered URL to select from.

#### Additional remarks

 

Adding new WebDAV-based databases did work flawlessly with Tusk version 2018.9.27. Existing setups continue to work - just adding a new database causes the issue.

#### Environment 

**Operating System:**
Linux (Ubuntu 24.04 LTS) as well as Windows 11 Pro

**Browser vendor and version:**
Firefox 129.0 as well as LibreWolf 128.0.3-2

**Storage Provider:**
Self-hosted WebDAV server (Apache2)

**Comment by subdavis** [comment]
You are not on the latest version.  Firefox latest version is `2024.8.6`

Please try again.

**Comment by oneffr** [comment]
You are right.

I forced ab update and now I rum 2024.8.6,, but, unfortunately, the issue remains...

**Comment by subdavis** [comment]
Thanks for checking, I'll look into it.

**Comment by SpookOz** [comment]
I'm getting a similar issue. Version 2024.8.10. Linux running Brave 1.68.137 Chromium: 127.0.6533.100. When I try to add a webdav file, I"m getting "Error: Invalid response: 401". It was actually working fine, then just started giving this error. Same browser version and Tusk version on a different machine works fine. Is this related? If not, I can open a new issue. Thanks.

**Comment by subdavis** [comment]
I've found that Tusk doesn't work with Digest auth on either Firefox or Chrome, and I have a fix for that.

However, if you're seeing something that works on Firefox and not chrome, I might need more info: what WebDAV server and auth method are you using?

**Comment by subdavis** [comment]
This was hopefully fixed in 2024.8.20 (on firefox)

@SpookOz @oneffr please LMK if that resolves it.

**Comment by oneffr** [comment]
Hi Brandon,

I can confirm: yes, that resolves my problem.

Thank you very much!

Regards


Oliver

------ Originalnachricht ------
Von "Brandon Davis" ***@***.***>
An "subdavis/Tusk" ***@***.***>
Cc "oneffr" ***@***.***>; "Mention" 
***@***.***>
Datum 22.08.2024 16:44:35
Betreff Re: [subdavis/Tusk] Cannot request origin permission for WebDAV 
server (Issue #351)
