### ISSUE TITLE
OTP not found

### ISSUE THREAD

**Issue by anhnmt** [subdavis/Tusk#353]
## Feature Request
![image](https://github.com/user-attachments/assets/456030cb-e1f8-419a-aa4b-f144ae85dbef)

In the old version I could still use OTP, but when I upgraded to the new version, the OTP disappeared.

Version 2024.8.7

**Comment by subdavis** [comment]
This will be fixed by https://github.com/subdavis/Tusk/pull/352

**Comment by subdavis** [comment]
This will be fixed in 2024.8.10 once it's been through the Chrome store review, probably tomorrow.
