### ISSUE TITLE
`invalid_request` when trying to authorise OneDrive

### ISSUE THREAD

**Issue by callumjethomas** [subdavis/Tusk#359]
### Steps to reproduce - current behaviour

When I try and authorise/reauthorise my OneDrive by clicking the [Authorise OneDrive] button/toggle under 'Manage Databases', I get the following error:

> We're unable to complete your request
> 
> invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

### What is the expected behaviour

Connect to Microsoft account/One Drive account authentication to sync my database file

### Environment 

**Operating System:** Windows 10 Enterprise v2H22

**Browser vendor and version:** Firefox 129.0.1 (64-bit)

**Storage Provider:** OneDrive

**Comment by subdavis** [comment]
Thank you for the report.  This should be fixed.

If necessary, visit https://account.live.com/consent to revoke Tusk and re-authenticate through Tusk Manage Databases.
