### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by KaKi87** [subdavis/Tusk#367]
### A feature you'd like to see
A dark theme

### Alternatives you've considered
None

### Additional remarks
None

---
Thanks

**Comment by subdavis** [comment]
Thanks for asking, but CSS theming is pretty annoying and just adds extra opportunities for something to go wrong.  I wouldn't accept a pull request even if someone else did the work.  Extra maintenance cost isn't worth it to me.

**Comment by KaKi87** [comment]
As everything on my machine is entirely dark, this would be the only white thing, and that blind me. Deal breaker. Could you please consider using an automated color inverter at least ?
