### ISSUE TITLE
v2018.1.2 `Error InvalidKey: invalid key` unlocking GDrive kdbx - Firefox 57.0.2

### ISSUE THREAD

**Issue by karlos1337** [subdavis/Tusk#47]
- [x] bug
- [ ] feature
- [ ] question

Cannot open password database from GDrive in Firefox Quantum 57.0.2, Tusk version v2018.1.2
Error: `Error InvalidKey: invalid key`
It works with same parameters and key file with Chrome and CKP extension v2017.5.30

Thanks for your work :)

**Comment by subdavis** [comment]
Yikes, that seems serious but it isn't much to go on. 

If you create a copy of the database in GDrive, are you able to open it?  What if you load it from another source, like a local read-only copy or from Dropbox?  How about a different database from google drive? 

When did you first begin using tusk?  Has this database worked before and was broken by version 2018.1.2?  Or did it just never work?

Debugging addons is _terrible_ in firefox, else I'd ask you to open the debug console.  

Thanks, and let's get this sorted out :)

**Comment by subdavis** [comment]
Note: I haven't strictly launched Tusk yet.  The Firefox version is an experimental dev build, and I've yet to release on the chrome web store.  I really appreciate folks like you who are willing to give it a whirl and report issues.

**Comment by subdavis** [comment]
@karlos1337 please download the latest tusk and try again.  I believe this is related to an issue with XML-based keyfiles fixed in version 2018.1.8

Thanks

**Comment by karlos1337** [comment]
Sorry about the time for answer, holidays, you know... 
I needed to manually remove and reinstall the extension but now everything works perfectly, thanks :)

**Comment by subdavis** [comment]
Great news, TY.
