### ISSUE TITLE
Slider does nothing

### ISSUE THREAD

**Issue by subdavis** [subdavis/Tusk#55]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

originally reported by @tonyrulez in #54 

### Please describe the current behavior, and explain why it's bad.

The time limit slider does nothing.

### Please describe how you think it should change.

It should absolutely cause credentials to be cached in memory

### Anything else?

Please provide me with some additional information:
1. Tusk version 2018.1.8
2. What browser is this?  the time slider bug I recently fixed only affected chrome.
3. If chrome/firefox and version >= 2018.1.7, could you check the popup window's debug console? Anything there?
4. Please describe what happens when you:
* sign in and select a remember period of 30 min.
* Close the popup but not the browser.
* open the popup again immediately
* open the popup in <60 seconds
* open the popup 3-5 min later.

**Comment by tonyrulez** [comment]
I'm using 2018.1.8 with Chrome. I'm sorry but I can't reproduce the problem, looks like it was my fault.

**Comment by subdavis** [comment]
@tonyrulez no worries, it was likely taken care of by an update.  Going to mark this as closed.
