### ISSUE TITLE
Add TOTP support

### ISSUE THREAD

**Issue by Rictusempra** [subdavis/Tusk#58]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Tusk does not detect TOTP code from entries

### Please describe how you think it should change.

KeePass can generate TOTP code from the KeeOTP plugin.

**Comment by subdavis** [comment]
I'll need to research this one a bit more.

I checked it out and https://sourceforge.net/projects/keeotp/ doesn't look like a very popular product.  No downloads this week and no updates since 2015.  This probably won't be a priority for me, but I'll leave the issue open for discussion.  Thanks.

**Comment by wavvs** [comment]
@subdavis TOTP come as out-of-the-box feature in [KeeWeb](https://github.com/keeweb/keeweb). It would be great if you implement this feature. KeeWeb is under MIT Licence, so you can, for example, integrate this [code](https://github.com/keeweb/keeweb/blob/4c4a308f9e19e29c240f54d99f64ad5d31639f25/app/scripts/util/otp.js) into your extension.

**Comment by subdavis** [comment]
Kick ass - I'll definitely try to work on this.

FYI, the underlying crypto engine for Tusk is keeweb/kdbxweb :)

**Comment by subdavis** [comment]
It was truly awesome how easy that was.

What do you think of this, @wavvs ?

![otp](https://user-images.githubusercontent.com/4214172/35255339-905859ae-ffbc-11e7-967d-707954f531e1.png)

**Comment by wavvs** [comment]
@subdavis Awesome, thank you :)

**Comment by subdavis** [comment]
Uploaded to chrome and Firefox stores, update should have this now.

Ty for the pointer.

**Comment by zmilonas** [comment]
I figured it out with some intuitive reading up on keeweb/keeweb. But it'd be useful for both to document how to add TOTP generation in an entry.

1. take a screenshot of the qr code
1. open an entry in keeweb
1. add a new custom field - `one-time password`
1. paste the screenshot of the qr code 
1. save the database.
1. use your totp in Tusk

**Comment by zmilonas** [comment]
We can close this for now I think. The fact that the whole of Tusk needs better documentation should be a seperate issue.
