### ISSUE TITLE
Ask for positive review or GH star on settings homepage.

### ISSUE THREAD

**Issue by subdavis** [subdavis/Tusk#60]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Nowhere for folks to share/support Tusk

### Please describe how you think it should change.

Don't want a donate box, but I think it would be OK to say "If you like tusk, leave a review or star the github repository".  Share on social media seems a little too much though

### Anything else?

I'd like feedback on this.  Would you be put off for a "Please leave a rating" at the bottom of the settings welcome page?

**Comment by jakes44** [comment]
I think a link to the repo for people to star and/or review wouldn't be a bad thing, as long as it's unobtrusive.

**Comment by subdavis** [comment]
Solved in #82
