### ISSUE TITLE
Tusk Periodically Requires Google Drive Reauthentication

### ISSUE THREAD

**Issue by necopinus** [subdavis/Tusk#64]
## This issue is a

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

When using a database stored on Google Drive, Tusk periodically looses its Google authentication data. This manifests when trying to unlock the database: After entering the database password, Tusk reports and error that "User interaction required." (If you have quick eyes, you can sometimes see the authentication UI start to open and then immediately close right before this error appears.) Switching to the settings, Google Drive will momentarily show up as busy, and then change to disabled with the same error message.

Re-enabling Google Drive works fine, after which the database stored there can be opened normally... At least until the next time that Tusk forget the Google login information.

It's hard to tell how long it takes for login information to be forgotten, but after some testing it appears to happen within ~30 minutes of when the database password itself expires. I've tried explicitly allowing both cookies and popups for Tusk, but to no avail. Perhaps the Google Drive authentication data is being cleared with the database password?

This issue occurs on a Chromebook when pulling a database off (G Suite) Google Drive (I'm testing right now to see if it's feasible to roll Tusk out to end-users at my work); other operating systems and storage mechanisms have not been tested.

### Please describe how you think it should change.

**Preferred:** Tusk should remember login information for Google Drive indefinitely (even if it forgets the database password).

**Second Best:** Tusk should correctly display a re-authentication prompt for Google Drive when it looses those credentials, rather than forcing the user to open up its settings and manually re-enabling Google Drive.

**Comment by subdavis** [comment]
G Suite huh?  I've not tested with a G suite account, but I'm unable to reproduce with a classic Google account.

Thanks for the detailed bug report.  I'll dig around and see what I can find.

I'll definitely put some priority on this if you're looking to roll it out in a corporate environment.

**Comment by sanicki** [comment]
> I've not tested with a G suite account, but I'm unable to reproduce with a classic Google account.

I'm experiencing the same issue using a G Suite Google Drive, FWIW.

**Comment by subdavis** [comment]
Looks like a great place to start then, thanks @sanicki

**Comment by subdavis** [comment]
Before I get too deep on this one, is the G Suite administrator on that account aware of https://support.google.com/a/answer/7281227?hl=en ?

Is it possible to whitelist Tusk and see if behavior changes?

**Comment by sanicki** [comment]
> Web applications—requires you to fill in the OAuth2 client ID

![screenshot 2018-01-13 at 12 09 19 pm](https://user-images.githubusercontent.com/6764844/34909242-9f6603f6-f85a-11e7-96cb-5eb166e87b48.png)

**Comment by subdavis** [comment]
`876467817034-rlas0hnb5jc9dt1qmp11l6g4724ktoqn.apps.googleusercontent.com`

**Comment by necopinus** [comment]
We're not currently using whitelists to limit API access, though we might in the future. That said, I'll take a look at this later tonight and report back.

**Comment by sanicki** [comment]
Whitelisted.

> It's hard to tell how long it takes for login information to be forgotten

This is also the case for me, so I'll report back when/if reauthentication is requested again.

**Comment by necopinus** [comment]
Initial testing is promising on my end, but requires a bit more testing. I'll report back on Monday (I haven't seen any "working state" last more than 24 hours, so waiting a bit more to be safe). Obviously if this starts failing, I'll report back sooner.

**Comment by sanicki** [comment]
Checked today after a reboot and unfortunately:

![screenshot 2018-01-14](https://user-images.githubusercontent.com/6764844/34917836-8940945c-f908-11e7-8e0f-d0a1578c5f56.jpg)

**Comment by necopinus** [comment]
Ditto.

**Comment by subdavis** [comment]
When you go back to setting -> manage databases -> enable Google, what parts of the Oauth prompt are skipped, if any?

In a full flow, you put in your username, password, and the have to click "Allow" to grant access.  Does all of that happen every time expiration occurs? If so, something is going on with Google.  If the "Allow" part is skipped, it might be something I can find and fix.

**Comment by necopinus** [comment]
When I log in again, I don't get the page asking me to allow Tusk access -- I only have to input username, password, and 2FA. So it looks like we're in the second case.

**Comment by subdavis** [comment]
I signed up for a GSuite account and was almost immediately able to reproduce.  The issue does not coincide with regular master password expiration.  It has nothing to do with Tusk "forgetting" its authorizaton token too quickly.  

What happens is this: A regular google account will allow you to perform a non-interactive Oauth flow when your token expires provided that your google password has not changed and you haven't revoked permissions on the app.  See https://developer.chrome.com/apps/identity#method-launchWebAuthFlow

1. Tusk caches a Token.
2. That token gets used for a while
3. That token naturally expires and when it does, requests go google API are met with 401.
4. When tusk sees a 401, it tries to perform a launchWebAuthFlow without an interactive session.
5. A normal google account will allow this.  A G Suite account, for whatever reason, won't.

I found some pretty vague docs @ https://developers.google.com/identity/protocols/OAuth2#expiration but I couldn't figure out how this applied to Tusk....  I think it has something to do with bullet 4 about 50 refresh tokens, but I can't work out how.

Working with Google / publishing this extension on their store has been a nightmare so far, so I don't expect much from reaching out to developer support.  I'm going to try and find out more about this, but I think the solution may fall under "Second Best" according to necopinus.

**Comment by subdavis** [comment]
I've got the basic implementation down.  I'll probably push it to the web store either tomorrow or Tuesday.

**Comment by necopinus** [comment]
Assuming you've pushed this, as I'm seeing a reauthorization page now instead of the error. Thank you!

One thing that has been tickling the back of my mind that may be helpful regarding the broader issue, and I just confirmed with one of my "beta" testers this morning:

When we initially started experimenting with KeePass, we rolled out [CKP](https://github.com/perfectapi/CKP) rather than Tusk, later switching when I learned that that project was unmaintained and subject to the [security vulnerability you outline on your blog](https://subdavis.com/blog/jekyll/update/2017/01/02/ckp-security-flaw.html). But I don't remember this issue occurring with CKP, and my tester confirms that indeed we only started to experience this after switching to Tusk.

So there's something that CKP is doing differently than Tusk that works around this issue. I have no idea, however, what that might be or if it can be ported back to Tusk.

Thank you again for you work on this!

**Comment by subdavis** [comment]
Without a single test, I'd imagine it has to do with https://github.com/perfectapi/CKP/blob/develop/services/googleDrivePasswordFileManager.js#L201

Ckp used to get tokens through a special Chrome browser API.  I ditched this for a method compatible with both chrome and Firefox .

apparently they aren't quite as interchangable as I had hoped.  In the future, it might be possible to set build flags to compile Tusk differently for chrome and FF. 

I'm going to leave this issue open until a better solution presents itself.  I appreciate all the time you've spent documenting your experience with this.

**Comment by evrydayzawrkday** [comment]
@subdavis - I actually *was* having the same issue as described here w/ the following setup:

- Windows 10x64 latest updates from MSFT
- Chrome v64
- Google Drive Consumer version, but 2FA is enabled on the Google account.

I just downloaded the Keepass plugin again and will comment back if I see this happen again. Prior it would require re-auth every 20-30 minutes to the Google Drive account.

**Comment by subdavis** [comment]
@evrydayzawrkday alright thanks for the feedback.  No idea why I'm unable to reproduce with a regular Google consumer account, but I figure the issue is prevalent enough to warrant a fix at this point.

Will report back when it's done.

**Comment by subdavis** [comment]
I've recently pushed use 2018.1.15 to the webstore.  

This will use chrome.identity.getAccessToken when google chrome is detected, then fallback to launchWebAuthFlow for unsupported browsers. 

@evrydayzawrkday @necopinus @sanicki Could you please verify that 2018.1.15 is installed and that this solves re-authentication for you?

Once we confirm that this issue is fixed, I'll kindly ask @necopinus to please close #64 out :)

**Comment by evrydayzawrkday** [comment]
@subdavis 

Will do. Using v2018.1.15, I got the following error about 5 minutes ago: 

"The authorization token for Google Drive has expired and Tusk was unable to refresh it. Please reauthorize below to continue to use Tusk with your database from Google Drive."

Re-authenticating fixed it, but I will wait for the webstore to update the version (still showing v2018.1.15) to give a final answer. What I did notice now is that even after I removed / reinstalled KeePass Tusk is that it did hold the Google Authentication. This very well could have been something in my old Google Chrome config, as this is a net-new install of Win10x64 as of last Friday.

**Comment by sanicki** [comment]
> Could you please verify that 2018.1.15 is installed and that this solves re-authentication for you?

Have updated. Haven't yet had to reauthenticate. Will update once I do. Thanks for the fast work.

**Comment by subdavis** [comment]
Please note that the first reauth may be a fluke caused by the API client transition.  A second reauth after 2018.1.15 would be cause for concern.

**Comment by evrydayzawrkday** [comment]
@subdavis 
No cigar. PC was off for about 5 1/2 hours and came back to the same issue as prior. See error attached:

![capture](https://user-images.githubusercontent.com/19562039/34969059-e9266738-fa3a-11e7-90cd-efdb53bf4ea8.PNG)

**Comment by subdavis** [comment]
@evrydayzawrkday that is decidedly something different.

Check out this snippit:
```
else {
  let err = chrome.runtime.lastError;
	if (!err) {
		err = new Error("Failed to authenticate.");
	}
	if (err.message == "OAuth2 not granted or revoked.") {
		//too confusing
		reject(new Error("You must Authorize google drive access to continue."))
	} else {
		reject(err);
	}
}
```

That error is only thrown when a user decides not to grant Tusk access to google Drive.  It comes straight from `chrome.runtime.lastError` - I don't think this one is my fault.

In other words, the blame for this one rests with Google.  It's entirely possible I've confused their servers by switching API clients.  

If you haven't already authorized, check out https://myaccount.google.com/permissions and see if Tusk is there. 

To reiterate, `You must Authorize google drive access to continue.` is an error message introduced in 2018.1.5 - you should have never seen it before today.  If you authorize again and this shows up again, I feel fully prepared to file this as a bug with Google.

**Comment by evrydayzawrkday** [comment]
@subdavis That is actually the error I have been getting since I saw this addon on /r/keepass, starting on 1/7/2017.

So what happens is that Google Drive for some reason de-authorizes the KeePass Tusk app (for whatever reason) and then simply tells me to re-auth with the error above. I have had my Chrome session closed for a bit since my last post and it has occurred again.

![image](https://user-images.githubusercontent.com/19562039/34970907-37aae906-fa45-11e7-99bb-09885c739e64.png)

Here are my Chrome settings: 
![image](https://user-images.githubusercontent.com/19562039/34970902-2ecee882-fa45-11e7-93d0-42a5a0a5a003.png)

**Comment by evrydayzawrkday** [comment]
@subdavis I think its fixed. This was a Chrome issue from what I could tell.

What I found is that Google Chrome profile (when you logon to sync your settings) auto-logged me out for some reason. Why I am unsure, but once I logged back in a second time my session has yet to expire and I am unable to repro this issue.

Sorry for the confusion, and thank you for the hard work on this project!

**Comment by evrydayzawrkday** [comment]
@subdavis + @necopinus 

I have confirmed.. after multiple reboots and other means that would normally break it prior, for me (using consumer Google Drive) was due to the way Google Chrome setup the profile. 

You can close this if it is now working for G Suite, as my issue is resolved.

Thank you @subdavis once again.

**Comment by necopinus** [comment]
@subdavis Into day 2 now with no error in sight on my end. I think you've done it.

Thanks for taking care of this so quickly. As requested, closing out.
