### ISSUE TITLE
A Way to Not Save Key file in Cache

### ISSUE THREAD

**Issue by gynet** [subdavis/Tusk#66]
Is there a way just to save the path of the key file instead of saving the key file in the browser cache?

**Comment by subdavis** [comment]
Nope.  This would involve giving Tusk direct filesystem access, which chrome stable does not support.

In the future, I would like to have an option to choose a keyfile from cloud storage same as the DB.

**Comment by subdavis** [comment]
Edit: Further reading:

https://developer.mozilla.org/en-US/docs/Web/API/FileSystem

It could probably be done in Chrome, but I generally dislike anything that isn't cross-compatible with Firefox
