### ISSUE TITLE
Resolve references in usernames/passwords

### ISSUE THREAD

**Issue by matidio** [subdavis/Tusk#72]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Tusk currently doesn't handle referenced usernames or password in Keepass database. E.g., {REF:U@T:Amazon} or {REF:P@T:Amazon}. Entries with referenced fields can't be used for autofill.

### Please describe how you think it should change.

In future username and password should be resolved.

**Comment by subdavis** [comment]
This is actually a bug.  References should be handled - this is a regression.

**Comment by subdavis** [comment]
@matidio I am unable to reproduce this issue.  I created an entry with Title Amazon and reproduced your examples exactly, and they worked.

Could you please provide an 
* exact title
* dummy username/password 
* website that these credentials should be tested on

And I'll dig in further.

**Comment by matidio** [comment]
@subdavis 
I used Amazon as an example because I observed the unresolved usernames/passwords with the records of our domains at work (didn't want to publish those). No need to go on the page itself. You can see the unresolved records in Tusk itself.
In the meanwhile I tried to hunt down the problem and I can reproduce it with the records in my Keepass database. Trying to isolate further the problem with these records I cannot reproduce it again as soon as I change the original record (record to be referenced). I suppose it is problem of the original record (entry in database) or the problem is very sophisticated. So it shouldn't be a widespread problem if at all. I propose to close the bug. I would reopen it if I can identify it completely. Thanks for your support.
PS: If you're interested in the records which produce this I can send you a test database with the records.

**Comment by subdavis** [comment]
Yeah I'm interested.  Check subdavis.com - feel free to choose any of those contact options.

Thanks for taking the time to report this.
