### ISSUE TITLE
Not working on Firefox for Android

### ISSUE THREAD

**Issue by berliozz** [subdavis/Tusk#74]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.
This extension successful installed to Firefox for Android, but when I try to go preferences of it, just show blank page by address: moz-extension://233df8b5-eacb-4544-bd77-a61f7de65c7e/options.html

### Please describe how you think it should change.
Settings screen as on desktop version of Firefox.

**Comment by subdavis** [comment]
This broke recently, I'll take a look.

I have no idea how to debug this though.  Add-ons for mobile are really odd.

**Comment by subdavis** [comment]
Found https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE - keeping that here for later

**Comment by berliozz** [comment]
Can you provide some information about date to fix this?
Now, we haven't any solution for Android version of Firefox.

**Comment by subdavis** [comment]
This is low priority to me.  The Android Firefox extension support is kind of terrible and doesn't provide a nice user experience.  I'd prefer that it didn't exist at all, but since it does, I'll try to fix it at some point.

If you want to use KeePass with Android, try keepass2android.

**Comment by yazhao** [comment]
keepass2android is designed for use within the apps rather than within the browser: k2a won't autofill if you're browsing on Firefox for Android

**Comment by Nurrl** [comment]
@Subdavis: I'll try to debug this ASAP, I'll inform you of my discoveries here.

**Comment by subdavis** [comment]
Found the problem.  Apparently Firefox android doesn't support `browser.identity`

https://github.com/mozilla/addons/issues/611#issuecomment-356025664 -> Docs don't mention this.

This will break almost every feature of Tusk - no google drive, dropbox, or onedrive.  You'll only have shared link support.  This issue isn't worth fixing - I'd rather document that Firefox for android is 100% unsupported than frustrate users with a half-ass experience. 

The next update will disable Tusk for android support - you won't be able to install it.

**Comment by Nurrl** [comment]
For what exactly `browser.identity` is used ? @subdavis

**Comment by subdavis** [comment]
Performing authentication with Google drive, Dropbox, etc.  It has a function called launchWebAuthFlow which triggers the login window to pop up.

**Comment by Nurrl** [comment]
So there is not workaround for oAuth ?

**Comment by Nurrl** [comment]
I'll take the example of https://github.com/keeweb/keeweb, which basically do the oAuth flow and work on android in firefox !

**Comment by subdavis** [comment]
Not to discourage you, but keeweb.info works differently.  They are capable of doing oAuth by performing a redirect directly to google and intercepting the callback in the browser.  

As an extension, we have no mechanism for redirects, which is why chrome.identity exists.  It run the redirect/intercept in the background for us.  If you want a browser based application, use KeeWeb.  This legitimately isn't possible with Tusk outside of some implementation where you authenticate on a website and then use the credentials to paste into Tusk.

**Comment by berliozz** [comment]
Maybe allow on android only local file? Data from Dropbox, Google, etc was storage to device and set as available offline. 
Yes, this descrease number of features, but allow using this extension.

**Comment by Nurrl** [comment]
Maybe there is a compatibility fix for those functions ?

**Comment by asvod** [comment]
It's still unsupported on FF mobile as of this post, sadly. 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity#Browser_compatibility
