### ISSUE TITLE
Google Drive, 2FA, and Organizational Emails

### ISSUE THREAD

**Issue by arkag** [subdavis/Tusk#75]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

Google Drive linking doesn't seem to work with my organizations email or the fact that I use 2FA

### Please describe how you think it should change.

Support this, please

**Comment by subdavis** [comment]
I use 2FA, this isn't a problem.  I've also verified that Tusk works with Google GSuite.

Please provide more details.  What errors do you get?  Can you post screenshots?  What browser what OS?

Thanks.

**Comment by subdavis** [comment]
Older than 7 days.  Closing do to inactivity: cant debug with so few details.
