### ISSUE TITLE
Update App Name in oAuth (at least Dropbox)

### ISSUE THREAD

**Issue by kevinmickey** [subdavis/Tusk#77]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

I installed on Firefox, and clicked to link Dropbox, then saw "CKPX - Chrome Keepass, Extended would like access to the files and folders in your Dropbox."

### Please describe how you think it should change.

Update to use "Tusk" instead of "CKPX"

**Comment by subdavis** [comment]
I'll re-check all my oAuth clients.  Thanks for the heads up.

**Comment by subdavis** [comment]
Quick update: there's no way to update that info in dropbox.  I would have to create a new application, push an update to the webstore, and re-apply for production use.

I've emailed dropbox support to get their help.  Thanks again.
