### ISSUE TITLE
Cannot use it on Firefox 57 on Android 8.0.0 !

### ISSUE THREAD

**Issue by Nurrl** [subdavis/Tusk#86]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

I cannot use this extension in FF 57 on Android O, When I got to Extension->Settings, It shows a blank page.

### Please describe how you think it should change.

It should work on Android, since this KeePass extension is very useful !

**Comment by subdavis** [comment]
Duplicate of #74
