### ISSUE TITLE
Updating local databases

### ISSUE THREAD

**Issue by joalaclancy** [subdavis/Tusk#88]
## This issue is a 

- [x] bug
- [ ] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

When using "File system" option for a Keepass database, any updates to the database require the user to remove and reupload the file to see changes.

### Please describe how you think it should change.

Add a button to re-upload the file from the same location from the main screen

**Comment by subdavis** [comment]
Hmm, this isn't intended.   Uploading a second time should cause an update.  I'll look into it.  Ty

**Comment by arkhipenko** [comment]
I second this issue - was just about to report it.
I am constantly synchronizing KBDX files across multiple platforms and also notices that a local tusk plugin will NOT display new entries until you manually remove and re-add the file store. Suspect some caching issue?
Thank you for looking into this. Grateful for all the work you do!

**Comment by subdavis** [comment]
A couple of notes on this issue.

1. It is not possible to have a "reload" button.  Browser extensions have no access to the user's filesystem.  If you want to easily update the database, please consider using dropbox or google drive.

2. I think I've fixed the issue where you have to remove the old database first. If you _must_ use local upload, you can open `settings -> manage databse` and simply re-upload the same database.  If it has the same name, it will update the copy that already existed.

**Comment by arkhipenko** [comment]
Thank you for looking into this!
