### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by IgelRM** [subdavis/Tusk#9]
Hello, thanks for continuing the development of the extension. @PaddeK started a pull request for WebDAV support but it never got finished (https://github.com/perfectapi/CKP/pull/98). It would be nice if you could implement it since I would like to use this with a NextCloud.

**Comment by subdavis** [comment]
@IgelRM Thanks for starting the discussion on this.  I'll take a look when I can, but I'd also love it if @PaddeK could open the PR again here.

I'm unfamiliar with NextCloud, but if they have an option to produce "Shared Links" or direct download links for individual files, it may already work.  Can you create links that work with `wget` / `cURL` ?

**Comment by IgelRM** [comment]
NextCloud uses [WebDav](https://en.wikipedia.org/wiki/WebDAV) for accessing files remotely. I would like it if accessing the file requires authentication.
`wget --user=username
--password=password https://cloud.domain.com/remote.php/webdav/database.kdbx`

(--no-check-certificate)

**Comment by subdavis** [comment]
Understood.  I've created the pull request, and I'll put the code through the paces soon.  Thanks.

**Comment by subdavis** [comment]
The code in #10 is somewhat half-baked and smells in places.  Adding Webdav support will be more involved than just merging some old code, and may take a bit.

**Comment by PaddeK** [comment]
Its definitely half-baked and just the bare minimum. If webdav support is wanted i would suggest to use a full-fledged and well tested library.

**Comment by Flore-mozfr** [comment]
Great feature, just installed the firefox extension and connected it to my nextcloud 13 server (following the best practices guidelines: good point to have mentioned that).
Works great, I could get rid off the additional keepass software on my computer (not my main).

Keep up the good work :+1:
