### ISSUE TITLE
Better support and documentation for Owncloud, Nextcloud

### ISSUE THREAD

**Issue by subdavis** [subdavis/Tusk#93]
## This issue is a 

- [ ] bug
- [x] feature
- [ ] question

### Please describe the current behavior, and explain why it's bad.

We don't describe how to use OwnCloud that well.

### Please describe how you think it should change.

It works, and we need to make the user experience better and guide users.

**Comment by alexfornuto** [comment]
I'm a new user, and would like to point Tusk at a DB stored on my Nextcloud server. @subdavis you seem to know how to do it. If you were to explain it, I'd happily make a PR to update the documentation.

I've tried adding the DB as a shared link, but I keep getting a network error. I've tried the regular and `/download` link, without a password protection on the share link.

**Comment by subdavis** [comment]
Yup, I've found the same issue Alex!  

While OwnCloud works, Nextcloud does an infinite 302 redirect.  It's an issue I'm working on, but it looks like a edge bug in NextCloud when you make a request with certain cookies set.

I'm working on a fix - this will be more than just a docs update.  Meanwhile I should note on the store and docs that Nextcloud is unsupported.

**Comment by subdavis** [comment]
Based on what I've learned, shared URLs from nextcloud are not to be trusted.

I'm going to merge this issue with #9 - this is in active development.

**Comment by alexfornuto** [comment]
Thanks for the update @subdavis. I know it's not relevant to the issue, but I'd be interested in hearing about what you discovered that leads you to say that Nextcloud shared URLs can't be trusted.

**Comment by subdavis** [comment]
Sorry I should have been more clear.

The lack of safety comes from it being very unreliable and prone to causing infinite redirects.  There are no security problems I've seen

**Comment by subdavis** [comment]
Final update:

This work is done and pushed to the web store for chrome/Firefox

Tusk now has full webDAV support for OwnCloud and Nextcloud.  Enjoy :)
